export interface LocationInfo {
  name: string;
  coordinates: [number, number];
  zoom: number;
  province?: string;
  type?: 'KOTA' | 'KABUPATEN' | 'PROVINSI' | 'KECAMATAN' | 'AREA';
}

export const INDONESIA_LOCATIONS: Record<string, LocationInfo> = {
  // ==========================================
  // 1. PROVINSI ACEH & KOTA/KABUPATEN
  // ==========================================
  aceh: {
    name: 'Provinsi Aceh',
    coordinates: [4.6951, 96.7494],
    zoom: 8,
    province: 'Aceh',
    type: 'PROVINSI',
  },
  'banda aceh': {
    name: 'Kota Banda Aceh',
    coordinates: [5.5483, 95.3238],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  sabang: {
    name: 'Kota Sabang',
    coordinates: [5.8920, 95.3180],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  lhokseumawe: {
    name: 'Kota Lhokseumawe',
    coordinates: [5.1801, 97.1408],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  langsa: {
    name: 'Kota Langsa',
    coordinates: [4.4716, 97.9683],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  subulussalam: {
    name: 'Kota Subulussalam',
    coordinates: [2.6397, 98.0044],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  meulaboh: {
    name: 'Meulaboh (Aceh Barat)',
    coordinates: [4.1449, 96.1285],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  'aceh besar': {
    name: 'Kabupaten Aceh Besar',
    coordinates: [5.3833, 95.5167],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh barat': {
    name: 'Kabupaten Aceh Barat',
    coordinates: [4.4500, 96.1667],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh tengah': {
    name: 'Kabupaten Aceh Tengah',
    coordinates: [4.6292, 96.8450],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  takengon: {
    name: 'Takengon (Aceh Tengah)',
    coordinates: [4.6292, 96.8450],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  pidie: {
    name: 'Kabupaten Pidie',
    coordinates: [5.3814, 95.9609],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  sigli: {
    name: 'Sigli (Pidie)',
    coordinates: [5.3814, 95.9609],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  'pidie jaya': {
    name: 'Kabupaten Pidie Jaya',
    coordinates: [5.2492, 96.2238],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  bireuen: {
    name: 'Kabupaten Bireuen',
    coordinates: [5.2044, 96.7009],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh utara': {
    name: 'Kabupaten Aceh Utara',
    coordinates: [5.0083, 97.1333],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh timur': {
    name: 'Kabupaten Aceh Timur',
    coordinates: [4.6258, 97.6433],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh selatan': {
    name: 'Kabupaten Aceh Selatan',
    coordinates: [3.2500, 97.3000],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  tapaktuan: {
    name: 'Tapaktuan (Aceh Selatan)',
    coordinates: [3.2575, 97.1812],
    zoom: 12,
    province: 'Aceh',
    type: 'KOTA',
  },
  'aceh singkil': {
    name: 'Kabupaten Aceh Singkil',
    coordinates: [2.3333, 97.8000],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'nagan raya': {
    name: 'Kabupaten Nagan Raya',
    coordinates: [4.1667, 96.5333],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  simeulue: {
    name: 'Kabupaten Simeulue',
    coordinates: [2.6167, 96.0833],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'bener meriah': {
    name: 'Kabupaten Bener Meriah',
    coordinates: [4.7417, 96.8667],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh jaya': {
    name: 'Kabupaten Aceh Jaya',
    coordinates: [4.7500, 95.6667],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh barat daya': {
    name: 'Kabupaten Aceh Barat Daya',
    coordinates: [3.7833, 96.9333],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'gayo lues': {
    name: 'Kabupaten Gayo Lues',
    coordinates: [3.9833, 97.3333],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },
  'aceh tamiang': {
    name: 'Kabupaten Aceh Tamiang',
    coordinates: [4.2500, 98.0500],
    zoom: 11,
    province: 'Aceh',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 2. SUMATERA UTARA
  // ==========================================
  'sumatera utara': {
    name: 'Provinsi Sumatera Utara',
    coordinates: [2.1154, 99.5451],
    zoom: 8,
    province: 'Sumatera Utara',
    type: 'PROVINSI',
  },
  sumut: {
    name: 'Provinsi Sumatera Utara',
    coordinates: [2.1154, 99.5451],
    zoom: 8,
    province: 'Sumatera Utara',
    type: 'PROVINSI',
  },
  medan: {
    name: 'Kota Medan',
    coordinates: [3.5952, 98.6722],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  binjai: {
    name: 'Kota Binjai',
    coordinates: [3.6006, 98.4854],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  pematangsiantar: {
    name: 'Kota Pematangsiantar',
    coordinates: [2.9619, 99.0687],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  siantar: {
    name: 'Kota Pematangsiantar',
    coordinates: [2.9619, 99.0687],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  'tebing tinggi': {
    name: 'Kota Tebing Tinggi',
    coordinates: [3.3285, 99.1625],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  tanjungbalai: {
    name: 'Kota Tanjungbalai',
    coordinates: [2.9667, 99.8000],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  sibolga: {
    name: 'Kota Sibolga',
    coordinates: [1.7426, 98.7792],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  'padang sidempuan': {
    name: 'Kota Padang Sidempuan',
    coordinates: [1.3734, 99.2687],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  gunungsitoli: {
    name: 'Kota Gunungsitoli',
    coordinates: [1.2828, 97.6152],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  'deli serdang': {
    name: 'Kabupaten Deli Serdang',
    coordinates: [3.5167, 98.6833],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  karo: {
    name: 'Kabupaten Karo (Sinabung)',
    coordinates: [3.1167, 98.5000],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  berastagi: {
    name: 'Berastagi (Karo)',
    coordinates: [3.1833, 98.5167],
    zoom: 12,
    province: 'Sumatera Utara',
    type: 'KOTA',
  },
  simalungun: {
    name: 'Kabupaten Simalungun',
    coordinates: [2.9500, 99.0000],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  toba: {
    name: 'Kabupaten Toba (Danau Toba)',
    coordinates: [2.3333, 99.2167],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  samosir: {
    name: 'Kabupaten Samosir',
    coordinates: [2.6000, 98.7167],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  asahan: {
    name: 'Kabupaten Asahan (Kisaran)',
    coordinates: [2.9833, 99.6167],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  labuhanbatu: {
    name: 'Kabupaten Labuhanbatu',
    coordinates: [2.1667, 99.9833],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  langkat: {
    name: 'Kabupaten Langkat',
    coordinates: [3.7500, 98.3167],
    zoom: 11,
    province: 'Sumatera Utara',
    type: 'KABUPATEN',
  },
  nias: {
    name: 'Kepulauan Nias',
    coordinates: [1.1000, 97.6000],
    zoom: 10,
    province: 'Sumatera Utara',
    type: 'AREA',
  },

  // ==========================================
  // 3. SUMATERA BARAT
  // ==========================================
  'sumatera barat': {
    name: 'Provinsi Sumatera Barat',
    coordinates: [-0.7399, 100.8000],
    zoom: 8,
    province: 'Sumatera Barat',
    type: 'PROVINSI',
  },
  sumbar: {
    name: 'Provinsi Sumatera Barat',
    coordinates: [-0.7399, 100.8000],
    zoom: 8,
    province: 'Sumatera Barat',
    type: 'PROVINSI',
  },
  padang: {
    name: 'Kota Padang',
    coordinates: [-0.9471, 100.4172],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  bukittinggi: {
    name: 'Kota Bukittinggi',
    coordinates: [-0.3056, 100.3692],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  payakumbuh: {
    name: 'Kota Payakumbuh',
    coordinates: [-0.2244, 100.6322],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  pariaman: {
    name: 'Kota Pariaman',
    coordinates: [-0.6264, 100.1207],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  solok: {
    name: 'Kota Solok',
    coordinates: [-0.7933, 100.6588],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  'padang panjang': {
    name: 'Kota Padang Panjang',
    coordinates: [-0.4639, 100.4419],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  sawahlunto: {
    name: 'Kota Sawahlunto',
    coordinates: [-0.6789, 100.7811],
    zoom: 12,
    province: 'Sumatera Barat',
    type: 'KOTA',
  },
  mentawai: {
    name: 'Kepulauan Mentawai',
    coordinates: [-2.1333, 99.5833],
    zoom: 9,
    province: 'Sumatera Barat',
    type: 'KABUPATEN',
  },
  agam: {
    name: 'Kabupaten Agam (Marapi)',
    coordinates: [-0.2500, 100.1667],
    zoom: 11,
    province: 'Sumatera Barat',
    type: 'KABUPATEN',
  },
  'tanah datar': {
    name: 'Kabupaten Tanah Datar',
    coordinates: [-0.4500, 100.5833],
    zoom: 11,
    province: 'Sumatera Barat',
    type: 'KABUPATEN',
  },
  'pesisir selatan': {
    name: 'Kabupaten Pesisir Selatan',
    coordinates: [-1.3500, 100.5667],
    zoom: 10,
    province: 'Sumatera Barat',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 4. RIAU & KEPULAUAN RIAU
  // ==========================================
  riau: {
    name: 'Provinsi Riau',
    coordinates: [0.5071, 101.4478],
    zoom: 8,
    province: 'Riau',
    type: 'PROVINSI',
  },
  pekanbaru: {
    name: 'Kota Pekanbaru',
    coordinates: [0.5071, 101.4478],
    zoom: 12,
    province: 'Riau',
    type: 'KOTA',
  },
  dumai: {
    name: 'Kota Dumai',
    coordinates: [1.6667, 101.4500],
    zoom: 12,
    province: 'Riau',
    type: 'KOTA',
  },
  duri: {
    name: 'Duri (Bengkalis)',
    coordinates: [1.2500, 101.2167],
    zoom: 12,
    province: 'Riau',
    type: 'AREA',
  },
  bengkalis: {
    name: 'Kabupaten Bengkalis',
    coordinates: [1.4833, 102.1000],
    zoom: 11,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  siak: {
    name: 'Kabupaten Siak Sri Indrapura',
    coordinates: [0.7950, 102.0494],
    zoom: 11,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  kampar: {
    name: 'Kabupaten Kampar (Bangkinang)',
    coordinates: [0.3333, 101.0333],
    zoom: 11,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  pelalawan: {
    name: 'Kabupaten Pelalawan',
    coordinates: [0.3500, 101.8500],
    zoom: 11,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  'rokan hilir': {
    name: 'Kabupaten Rokan Hilir',
    coordinates: [2.1500, 100.8000],
    zoom: 10,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  'indragiri hilir': {
    name: 'Kabupaten Indragiri Hilir',
    coordinates: [-0.3167, 103.1500],
    zoom: 10,
    province: 'Riau',
    type: 'KABUPATEN',
  },
  'kepulauan riau': {
    name: 'Provinsi Kepulauan Riau',
    coordinates: [3.9456, 108.1428],
    zoom: 8,
    province: 'Kepulauan Riau',
    type: 'PROVINSI',
  },
  kepri: {
    name: 'Provinsi Kepulauan Riau',
    coordinates: [3.9456, 108.1428],
    zoom: 8,
    province: 'Kepulauan Riau',
    type: 'PROVINSI',
  },
  batam: {
    name: 'Kota Batam',
    coordinates: [1.1301, 104.0529],
    zoom: 12,
    province: 'Kepulauan Riau',
    type: 'KOTA',
  },
  tanjungpinang: {
    name: 'Kota Tanjungpinang',
    coordinates: [0.9167, 104.4500],
    zoom: 12,
    province: 'Kepulauan Riau',
    type: 'KOTA',
  },
  bintan: {
    name: 'Kabupaten Bintan',
    coordinates: [1.0500, 104.4833],
    zoom: 11,
    province: 'Kepulauan Riau',
    type: 'KABUPATEN',
  },
  karimun: {
    name: 'Kabupaten Karimun',
    coordinates: [1.0000, 103.4000],
    zoom: 11,
    province: 'Kepulauan Riau',
    type: 'KABUPATEN',
  },
  natuna: {
    name: 'Kabupaten Natuna (Ranai)',
    coordinates: [3.9456, 108.1428],
    zoom: 9,
    province: 'Kepulauan Riau',
    type: 'KABUPATEN',
  },
  anambas: {
    name: 'Kepulauan Anambas',
    coordinates: [3.2167, 106.2167],
    zoom: 10,
    province: 'Kepulauan Riau',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 5. JAMBI
  // ==========================================
  jambi: {
    name: 'Provinsi Jambi',
    coordinates: [-1.6101, 103.6131],
    zoom: 8,
    province: 'Jambi',
    type: 'PROVINSI',
  },
  'kota jambi': {
    name: 'Kota Jambi',
    coordinates: [-1.6101, 103.6131],
    zoom: 12,
    province: 'Jambi',
    type: 'KOTA',
  },
  'sungai penuh': {
    name: 'Kota Sungai Penuh',
    coordinates: [-2.0667, 101.3833],
    zoom: 12,
    province: 'Jambi',
    type: 'KOTA',
  },
  kerinci: {
    name: 'Kabupaten Kerinci (Gunung Kerinci)',
    coordinates: [-2.0833, 101.5000],
    zoom: 11,
    province: 'Jambi',
    type: 'KABUPATEN',
  },
  bungo: {
    name: 'Kabupaten Bungo (Muara Bungo)',
    coordinates: [-1.5000, 101.9667],
    zoom: 11,
    province: 'Jambi',
    type: 'KABUPATEN',
  },
  merangin: {
    name: 'Kabupaten Merangin (Bangko)',
    coordinates: [-2.1000, 102.2667],
    zoom: 11,
    province: 'Jambi',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 6. SUMATERA SELATAN & BANGKA BELITUNG
  // ==========================================
  'sumatera selatan': {
    name: 'Provinsi Sumatera Selatan',
    coordinates: [-3.3194, 104.1698],
    zoom: 8,
    province: 'Sumatera Selatan',
    type: 'PROVINSI',
  },
  sumsel: {
    name: 'Provinsi Sumatera Selatan',
    coordinates: [-3.3194, 104.1698],
    zoom: 8,
    province: 'Sumatera Selatan',
    type: 'PROVINSI',
  },
  palembang: {
    name: 'Kota Palembang',
    coordinates: [-2.9761, 104.7754],
    zoom: 12,
    province: 'Sumatera Selatan',
    type: 'KOTA',
  },
  prabumulih: {
    name: 'Kota Prabumulih',
    coordinates: [-3.4333, 104.2333],
    zoom: 12,
    province: 'Sumatera Selatan',
    type: 'KOTA',
  },
  lubuklinggau: {
    name: 'Kota Lubuklinggau',
    coordinates: [-3.2961, 102.8617],
    zoom: 12,
    province: 'Sumatera Selatan',
    type: 'KOTA',
  },
  'pagar alam': {
    name: 'Kota Pagar Alam (Dempo)',
    coordinates: [-4.0306, 103.2689],
    zoom: 12,
    province: 'Sumatera Selatan',
    type: 'KOTA',
  },
  lahat: {
    name: 'Kabupaten Lahat',
    coordinates: [-3.7833, 103.5333],
    zoom: 11,
    province: 'Sumatera Selatan',
    type: 'KABUPATEN',
  },
  'muara enim': {
    name: 'Kabupaten Muara Enim',
    coordinates: [-3.6500, 103.7833],
    zoom: 11,
    province: 'Sumatera Selatan',
    type: 'KABUPATEN',
  },
  banyuasin: {
    name: 'Kabupaten Banyuasin',
    coordinates: [-2.8833, 104.3833],
    zoom: 10,
    province: 'Sumatera Selatan',
    type: 'KABUPATEN',
  },
  'ogan ilir': {
    name: 'Kabupaten Ogan Ilir (Indralaya)',
    coordinates: [-3.2667, 104.6500],
    zoom: 11,
    province: 'Sumatera Selatan',
    type: 'KABUPATEN',
  },
  'bangka belitung': {
    name: 'Provinsi Kepulauan Bangka Belitung',
    coordinates: [-2.7410, 106.4406],
    zoom: 8,
    province: 'Bangka Belitung',
    type: 'PROVINSI',
  },
  babel: {
    name: 'Provinsi Kepulauan Bangka Belitung',
    coordinates: [-2.7410, 106.4406],
    zoom: 8,
    province: 'Bangka Belitung',
    type: 'PROVINSI',
  },
  pangkalpinang: {
    name: 'Kota Pangkalpinang',
    coordinates: [-2.1290, 106.1139],
    zoom: 12,
    province: 'Bangka Belitung',
    type: 'KOTA',
  },
  belitung: {
    name: 'Pulau Belitung (Tanjung Pandan)',
    coordinates: [-2.7500, 107.7500],
    zoom: 10,
    province: 'Bangka Belitung',
    type: 'AREA',
  },
  bangka: {
    name: 'Pulau Bangka (Sungailiat)',
    coordinates: [-1.8500, 106.1167],
    zoom: 10,
    province: 'Bangka Belitung',
    type: 'AREA',
  },

  // ==========================================
  // 7. BENGKULU
  // ==========================================
  bengkulu: {
    name: 'Provinsi Bengkulu',
    coordinates: [-3.8004, 102.2655],
    zoom: 8,
    province: 'Bengkulu',
    type: 'PROVINSI',
  },
  'kota bengkulu': {
    name: 'Kota Bengkulu',
    coordinates: [-3.8004, 102.2655],
    zoom: 12,
    province: 'Bengkulu',
    type: 'KOTA',
  },
  curup: {
    name: 'Curup (Rejang Lebong)',
    coordinates: [-3.4722, 102.5283],
    zoom: 12,
    province: 'Bengkulu',
    type: 'KOTA',
  },
  mukomuko: {
    name: 'Kabupaten Mukomuko',
    coordinates: [-2.5833, 101.1167],
    zoom: 10,
    province: 'Bengkulu',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 8. LAMPUNG
  // ==========================================
  lampung: {
    name: 'Provinsi Lampung',
    coordinates: [-5.4297, 105.2625],
    zoom: 8,
    province: 'Lampung',
    type: 'PROVINSI',
  },
  'bandar lampung': {
    name: 'Kota Bandar Lampung',
    coordinates: [-5.4297, 105.2625],
    zoom: 12,
    province: 'Lampung',
    type: 'KOTA',
  },
  metro: {
    name: 'Kota Metro',
    coordinates: [-5.1131, 105.3069],
    zoom: 12,
    province: 'Lampung',
    type: 'KOTA',
  },
  'lampung selatan': {
    name: 'Kabupaten Lampung Selatan (Kalianda)',
    coordinates: [-5.7333, 105.5833],
    zoom: 11,
    province: 'Lampung',
    type: 'KABUPATEN',
  },
  bakauheni: {
    name: 'Pelabuhan Bakauheni',
    coordinates: [-5.8711, 105.7533],
    zoom: 13,
    province: 'Lampung',
    type: 'AREA',
  },
  'lampung tengah': {
    name: 'Kabupaten Lampung Tengah',
    coordinates: [-4.9000, 105.2167],
    zoom: 10,
    province: 'Lampung',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 9. DKI JAKARTA
  // ==========================================
  jakarta: {
    name: 'DKI Jakarta',
    coordinates: [-6.2088, 106.8456],
    zoom: 11,
    province: 'DKI Jakarta',
    type: 'PROVINSI',
  },
  'dki jakarta': {
    name: 'DKI Jakarta',
    coordinates: [-6.2088, 106.8456],
    zoom: 11,
    province: 'DKI Jakarta',
    type: 'PROVINSI',
  },
  'jakarta pusat': {
    name: 'Kota Jakarta Pusat',
    coordinates: [-6.1805, 106.8284],
    zoom: 13,
    province: 'DKI Jakarta',
    type: 'KOTA',
  },
  'jakarta selatan': {
    name: 'Kota Jakarta Selatan',
    coordinates: [-6.2615, 106.8106],
    zoom: 13,
    province: 'DKI Jakarta',
    type: 'KOTA',
  },
  'jakarta timur': {
    name: 'Kota Jakarta Timur',
    coordinates: [-6.2250, 106.9004],
    zoom: 13,
    province: 'DKI Jakarta',
    type: 'KOTA',
  },
  'jakarta barat': {
    name: 'Kota Jakarta Barat',
    coordinates: [-6.1683, 106.7589],
    zoom: 13,
    province: 'DKI Jakarta',
    type: 'KOTA',
  },
  'jakarta utara': {
    name: 'Kota Jakarta Utara',
    coordinates: [-6.1214, 106.7741],
    zoom: 13,
    province: 'DKI Jakarta',
    type: 'KOTA',
  },
  'kepulauan seribu': {
    name: 'Kabupaten Kepulauan Seribu',
    coordinates: [-5.6122, 106.5622],
    zoom: 11,
    province: 'DKI Jakarta',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 10. JAWA BARAT
  // ==========================================
  'jawa barat': {
    name: 'Provinsi Jawa Barat',
    coordinates: [-6.9175, 107.6191],
    zoom: 8,
    province: 'Jawa Barat',
    type: 'PROVINSI',
  },
  jabar: {
    name: 'Provinsi Jawa Barat',
    coordinates: [-6.9175, 107.6191],
    zoom: 8,
    province: 'Jawa Barat',
    type: 'PROVINSI',
  },
  bandung: {
    name: 'Kota Bandung',
    coordinates: [-6.9175, 107.6191],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  cimahi: {
    name: 'Kota Cimahi',
    coordinates: [-6.8722, 107.5422],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  'kabupaten bandung': {
    name: 'Kabupaten Bandung (Soreang)',
    coordinates: [-7.0253, 107.5197],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  'bandung barat': {
    name: 'Kabupaten Bandung Barat (Ngamprah)',
    coordinates: [-6.8444, 107.4950],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  bogor: {
    name: 'Kota Bogor',
    coordinates: [-6.5971, 106.8060],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  'kabupaten bogor': {
    name: 'Kabupaten Bogor (Cibinong)',
    coordinates: [-6.4833, 106.8500],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  depok: {
    name: 'Kota Depok',
    coordinates: [-6.4025, 106.7942],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  bekasi: {
    name: 'Kota Bekasi',
    coordinates: [-6.2383, 106.9756],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  'kabupaten bekasi': {
    name: 'Kabupaten Bekasi (Cikarang)',
    coordinates: [-6.3639, 107.1706],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  cikarang: {
    name: 'Cikarang (Bekasi)',
    coordinates: [-6.3150, 107.1436],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'AREA',
  },
  sukabumi: {
    name: 'Kota Sukabumi',
    coordinates: [-6.9277, 106.9300],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  cianjur: {
    name: 'Kabupaten Cianjur',
    coordinates: [-6.8174, 107.1394],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  cirebon: {
    name: 'Kota Cirebon',
    coordinates: [-6.7320, 108.5523],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  tasikmalaya: {
    name: 'Kota Tasikmalaya',
    coordinates: [-7.3274, 108.2207],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  garut: {
    name: 'Kabupaten Garut',
    coordinates: [-7.2278, 107.9087],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  karawang: {
    name: 'Kabupaten Karawang',
    coordinates: [-6.3000, 107.3000],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  purwakarta: {
    name: 'Kabupaten Purwakarta',
    coordinates: [-6.5569, 107.4433],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  subang: {
    name: 'Kabupaten Subang',
    coordinates: [-6.5716, 107.7587],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  indramayu: {
    name: 'Kabupaten Indramayu',
    coordinates: [-6.3264, 108.3200],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  sumedang: {
    name: 'Kabupaten Sumedang',
    coordinates: [-6.8586, 107.9267],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  majalengka: {
    name: 'Kabupaten Majalengka',
    coordinates: [-6.8361, 108.2278],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  kuningan: {
    name: 'Kabupaten Kuningan',
    coordinates: [-6.9764, 108.4839],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  ciamis: {
    name: 'Kabupaten Ciamis',
    coordinates: [-7.3264, 108.3533],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  banjar: {
    name: 'Kota Banjar',
    coordinates: [-7.3700, 108.5333],
    zoom: 12,
    province: 'Jawa Barat',
    type: 'KOTA',
  },
  pangandaran: {
    name: 'Kabupaten Pangandaran',
    coordinates: [-7.6833, 108.6500],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'KABUPATEN',
  },
  dayeuhkolot: {
    name: 'Dayeuhkolot (Bandung)',
    coordinates: [-6.9856, 107.6256],
    zoom: 13,
    province: 'Jawa Barat',
    type: 'KECAMATAN',
  },
  baleendah: {
    name: 'Baleendah (Bandung)',
    coordinates: [-7.0084, 107.6322],
    zoom: 13,
    province: 'Jawa Barat',
    type: 'KECAMATAN',
  },
  lembang: {
    name: 'Lembang (Bandung Barat)',
    coordinates: [-6.8152, 107.6186],
    zoom: 13,
    province: 'Jawa Barat',
    type: 'KECAMATAN',
  },
  gedebage: {
    name: 'Gedebage (Bandung)',
    coordinates: [-6.9450, 107.6890],
    zoom: 13,
    province: 'Jawa Barat',
    type: 'KECAMATAN',
  },
  pasteur: {
    name: 'Pasteur (Bandung)',
    coordinates: [-6.8943, 107.5925],
    zoom: 13,
    province: 'Jawa Barat',
    type: 'AREA',
  },
  cipularang: {
    name: 'Tol Cipularang',
    coordinates: [-6.6433, 107.4124],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'AREA',
  },
  padaleunyi: {
    name: 'Tol Padaleunyi',
    coordinates: [-6.9500, 107.6000],
    zoom: 11,
    province: 'Jawa Barat',
    type: 'AREA',
  },

  // ==========================================
  // 11. BANTEN
  // ==========================================
  banten: {
    name: 'Provinsi Banten',
    coordinates: [-6.4058, 106.0640],
    zoom: 9,
    province: 'Banten',
    type: 'PROVINSI',
  },
  serang: {
    name: 'Kota Serang',
    coordinates: [-6.1200, 106.1503],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  cilegon: {
    name: 'Kota Cilegon',
    coordinates: [-5.9984, 106.0275],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  merak: {
    name: 'Pelabuhan Merak (Cilegon)',
    coordinates: [-5.9317, 105.9983],
    zoom: 12,
    province: 'Banten',
    type: 'AREA',
  },
  tangerang: {
    name: 'Kota Tangerang',
    coordinates: [-6.1783, 106.6319],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  'tangerang selatan': {
    name: 'Kota Tangerang Selatan',
    coordinates: [-6.2889, 106.7178],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  tangsel: {
    name: 'Kota Tangerang Selatan (Tangsel)',
    coordinates: [-6.2889, 106.7178],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  pandeglang: {
    name: 'Kabupaten Pandeglang',
    coordinates: [-6.5367, 105.8349],
    zoom: 11,
    province: 'Banten',
    type: 'KABUPATEN',
  },
  lebak: {
    name: 'Kabupaten Lebak',
    coordinates: [-6.6436, 106.2529],
    zoom: 10,
    province: 'Banten',
    type: 'KABUPATEN',
  },
  rangkasbitung: {
    name: 'Rangkasbitung (Lebak)',
    coordinates: [-6.3611, 106.2483],
    zoom: 12,
    province: 'Banten',
    type: 'KOTA',
  },
  bayah: {
    name: 'Bayah (Banten Selatan)',
    coordinates: [-6.9288, 106.2529],
    zoom: 11,
    province: 'Banten',
    type: 'KECAMATAN',
  },

  // ==========================================
  // 12. JAWA TENGAH
  // ==========================================
  'jawa tengah': {
    name: 'Provinsi Jawa Tengah',
    coordinates: [-7.1510, 110.1403],
    zoom: 8,
    province: 'Jawa Tengah',
    type: 'PROVINSI',
  },
  jateng: {
    name: 'Provinsi Jawa Tengah',
    coordinates: [-7.1510, 110.1403],
    zoom: 8,
    province: 'Jawa Tengah',
    type: 'PROVINSI',
  },
  semarang: {
    name: 'Kota Semarang',
    coordinates: [-6.9667, 110.4167],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  surakarta: {
    name: 'Kota Surakarta (Solo)',
    coordinates: [-7.5755, 110.8243],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  solo: {
    name: 'Kota Surakarta (Solo)',
    coordinates: [-7.5755, 110.8243],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  salatiga: {
    name: 'Kota Salatiga',
    coordinates: [-7.3305, 110.5084],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  magelang: {
    name: 'Kota Magelang',
    coordinates: [-7.4706, 110.2178],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  pekalongan: {
    name: 'Kota Pekalongan',
    coordinates: [-6.8886, 109.6753],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  tegal: {
    name: 'Kota Tegal',
    coordinates: [-6.8694, 109.1402],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  purwokerto: {
    name: 'Purwokerto (Banyumas)',
    coordinates: [-7.4244, 109.2300],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KOTA',
  },
  banyumas: {
    name: 'Kabupaten Banyumas',
    coordinates: [-7.5167, 109.2833],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  cilacap: {
    name: 'Kabupaten Cilacap',
    coordinates: [-7.7167, 109.0167],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  kudus: {
    name: 'Kabupaten Kudus',
    coordinates: [-6.8047, 110.8406],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  jepara: {
    name: 'Kabupaten Jepara',
    coordinates: [-6.5911, 110.6778],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  demak: {
    name: 'Kabupaten Demak',
    coordinates: [-6.8944, 110.6389],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  kendal: {
    name: 'Kabupaten Kendal',
    coordinates: [-6.9247, 110.2036],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  batang: {
    name: 'Kabupaten Batang',
    coordinates: [-6.9083, 109.7289],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  brebes: {
    name: 'Kabupaten Brebes',
    coordinates: [-6.8711, 109.0428],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  kebumen: {
    name: 'Kabupaten Kebumen',
    coordinates: [-7.6697, 109.6522],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  purworejo: {
    name: 'Kabupaten Purworejo',
    coordinates: [-7.7144, 110.0089],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  wonosobo: {
    name: 'Kabupaten Wonosobo (Dieng)',
    coordinates: [-7.3639, 109.9000],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  boyolali: {
    name: 'Kabupaten Boyolali',
    coordinates: [-7.5333, 110.5956],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  klaten: {
    name: 'Kabupaten Klaten',
    coordinates: [-7.7056, 110.6053],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  sukoharjo: {
    name: 'Kabupaten Sukoharjo',
    coordinates: [-7.6833, 110.8333],
    zoom: 12,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  wonogiri: {
    name: 'Kabupaten Wonogiri',
    coordinates: [-7.8167, 110.9250],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  karanganyar: {
    name: 'Kabupaten Karanganyar (Lawu)',
    coordinates: [-7.5967, 110.9517],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  sragen: {
    name: 'Kabupaten Sragen',
    coordinates: [-7.4278, 111.0222],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  blora: {
    name: 'Kabupaten Blora (Cepu)',
    coordinates: [-6.9697, 111.4186],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  rembang: {
    name: 'Kabupaten Rembang',
    coordinates: [-6.7111, 111.3417],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },
  pati: {
    name: 'Kabupaten Pati',
    coordinates: [-6.7558, 111.0378],
    zoom: 11,
    province: 'Jawa Tengah',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 13. D.I. YOGYAKARTA
  // ==========================================
  'daerah istimewa yogyakarta': {
    name: 'D.I. Yogyakarta',
    coordinates: [-7.7956, 110.3695],
    zoom: 10,
    province: 'D.I. Yogyakarta',
    type: 'PROVINSI',
  },
  diy: {
    name: 'D.I. Yogyakarta',
    coordinates: [-7.7956, 110.3695],
    zoom: 10,
    province: 'D.I. Yogyakarta',
    type: 'PROVINSI',
  },
  yogyakarta: {
    name: 'Kota Yogyakarta',
    coordinates: [-7.7956, 110.3695],
    zoom: 12,
    province: 'D.I. Yogyakarta',
    type: 'KOTA',
  },
  jogja: {
    name: 'Kota Yogyakarta',
    coordinates: [-7.7956, 110.3695],
    zoom: 12,
    province: 'D.I. Yogyakarta',
    type: 'KOTA',
  },
  sleman: {
    name: 'Kabupaten Sleman (Merapi)',
    coordinates: [-7.7156, 110.3556],
    zoom: 12,
    province: 'D.I. Yogyakarta',
    type: 'KABUPATEN',
  },
  bantul: {
    name: 'Kabupaten Bantul (Opak)',
    coordinates: [-7.8889, 110.3289],
    zoom: 12,
    province: 'D.I. Yogyakarta',
    type: 'KABUPATEN',
  },
  gunungkidul: {
    name: 'Kabupaten Gunungkidul (Wonosari)',
    coordinates: [-7.9625, 110.6033],
    zoom: 11,
    province: 'D.I. Yogyakarta',
    type: 'KABUPATEN',
  },
  'kulon progo': {
    name: 'Kabupaten Kulon Progo (YIA)',
    coordinates: [-7.8572, 110.1583],
    zoom: 11,
    province: 'D.I. Yogyakarta',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 14. JAWA TIMUR
  // ==========================================
  'jawa timur': {
    name: 'Provinsi Jawa Timur',
    coordinates: [-7.5361, 112.2384],
    zoom: 8,
    province: 'Jawa Timur',
    type: 'PROVINSI',
  },
  jatim: {
    name: 'Provinsi Jawa Timur',
    coordinates: [-7.5361, 112.2384],
    zoom: 8,
    province: 'Jawa Timur',
    type: 'PROVINSI',
  },
  surabaya: {
    name: 'Kota Surabaya',
    coordinates: [-7.2575, 112.7521],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  malang: {
    name: 'Kota Malang',
    coordinates: [-7.9666, 112.6326],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  batu: {
    name: 'Kota Batu',
    coordinates: [-7.8700, 112.5272],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  sidoarjo: {
    name: 'Kabupaten Sidoarjo (Porong)',
    coordinates: [-7.4478, 112.7183],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  gresik: {
    name: 'Kabupaten Gresik',
    coordinates: [-7.1566, 112.6555],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  mojokerto: {
    name: 'Kota Mojokerto',
    coordinates: [-7.4725, 112.4339],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  pasuruan: {
    name: 'Kota Pasuruan',
    coordinates: [-7.6453, 112.9075],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  probolinggo: {
    name: 'Kota Probolinggo (Bromo)',
    coordinates: [-7.7543, 113.2159],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  kediri: {
    name: 'Kota Kediri (Kelud)',
    coordinates: [-7.8167, 112.0167],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  blitar: {
    name: 'Kota Blitar',
    coordinates: [-8.0983, 112.1681],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  madiun: {
    name: 'Kota Madiun',
    coordinates: [-7.6298, 111.5239],
    zoom: 12,
    province: 'Jawa Timur',
    type: 'KOTA',
  },
  jember: {
    name: 'Kabupaten Jember',
    coordinates: [-8.1724, 113.6995],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  banyuwangi: {
    name: 'Kabupaten Banyuwangi (Ijen)',
    coordinates: [-8.2192, 114.3691],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  tuban: {
    name: 'Kabupaten Tuban',
    coordinates: [-6.8976, 112.0649],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  lamongan: {
    name: 'Kabupaten Lamongan',
    coordinates: [-7.1206, 112.4158],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  bojonegoro: {
    name: 'Kabupaten Bojonegoro (Bengawan Solo)',
    coordinates: [-7.1502, 111.8817],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  ngawi: {
    name: 'Kabupaten Ngawi',
    coordinates: [-7.4042, 111.4461],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  ponorogo: {
    name: 'Kabupaten Ponorogo',
    coordinates: [-7.8686, 111.4622],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  pacitan: {
    name: 'Kabupaten Pacitan',
    coordinates: [-8.1969, 111.1078],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  tulungagung: {
    name: 'Kabupaten Tulungagung',
    coordinates: [-8.0667, 111.9000],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  lumajang: {
    name: 'Kabupaten Lumajang (Semeru)',
    coordinates: [-8.1333, 113.2247],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  situbondo: {
    name: 'Kabupaten Situbondo',
    coordinates: [-7.7061, 114.0053],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  madura: {
    name: 'Pulau Madura',
    coordinates: [-7.0500, 113.4000],
    zoom: 10,
    province: 'Jawa Timur',
    type: 'AREA',
  },
  bangkalan: {
    name: 'Kabupaten Bangkalan',
    coordinates: [-7.0306, 112.7486],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  sampang: {
    name: 'Kabupaten Sampang',
    coordinates: [-7.1833, 113.2500],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  pamekasan: {
    name: 'Kabupaten Pamekasan',
    coordinates: [-7.1606, 113.4839],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },
  sumenep: {
    name: 'Kabupaten Sumenep',
    coordinates: [-7.0167, 113.8667],
    zoom: 11,
    province: 'Jawa Timur',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 15. BALI
  // ==========================================
  bali: {
    name: 'Provinsi Bali',
    coordinates: [-8.4095, 115.1889],
    zoom: 10,
    province: 'Bali',
    type: 'PROVINSI',
  },
  denpasar: {
    name: 'Kota Denpasar',
    coordinates: [-8.6705, 115.2126],
    zoom: 12,
    province: 'Bali',
    type: 'KOTA',
  },
  badung: {
    name: 'Kabupaten Badung (Kuta/Seminyak)',
    coordinates: [-8.5833, 115.1833],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  kuta: {
    name: 'Kuta (Badung, Bali)',
    coordinates: [-8.7233, 115.1725],
    zoom: 13,
    province: 'Bali',
    type: 'AREA',
  },
  ubud: {
    name: 'Ubud (Gianyar, Bali)',
    coordinates: [-8.5069, 115.2625],
    zoom: 13,
    province: 'Bali',
    type: 'AREA',
  },
  gianyar: {
    name: 'Kabupaten Gianyar',
    coordinates: [-8.5444, 115.3267],
    zoom: 12,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  tabanan: {
    name: 'Kabupaten Tabanan',
    coordinates: [-8.5383, 115.1239],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  buleleng: {
    name: 'Kabupaten Buleleng (Singaraja)',
    coordinates: [-8.1122, 115.0883],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  singaraja: {
    name: 'Singaraja (Buleleng)',
    coordinates: [-8.1122, 115.0883],
    zoom: 12,
    province: 'Bali',
    type: 'KOTA',
  },
  karangasem: {
    name: 'Kabupaten Karangasem (Gunung Agung)',
    coordinates: [-8.3833, 115.5333],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  klungkung: {
    name: 'Kabupaten Klungkung (Nusa Penida)',
    coordinates: [-8.5333, 115.4000],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  bangli: {
    name: 'Kabupaten Bangli (Batur)',
    coordinates: [-8.2500, 115.3500],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },
  jembrana: {
    name: 'Kabupaten Jembrana (Negara)',
    coordinates: [-8.2833, 114.6167],
    zoom: 11,
    province: 'Bali',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 16. NUSA TENGGARA BARAT
  // ==========================================
  'nusa tenggara barat': {
    name: 'Provinsi Nusa Tenggara Barat',
    coordinates: [-8.6529, 117.3616],
    zoom: 8,
    province: 'Nusa Tenggara Barat',
    type: 'PROVINSI',
  },
  ntb: {
    name: 'Provinsi Nusa Tenggara Barat',
    coordinates: [-8.6529, 117.3616],
    zoom: 8,
    province: 'Nusa Tenggara Barat',
    type: 'PROVINSI',
  },
  mataram: {
    name: 'Kota Mataram',
    coordinates: [-8.5799, 116.0999],
    zoom: 12,
    province: 'Nusa Tenggara Barat',
    type: 'KOTA',
  },
  bima: {
    name: 'Kota Bima',
    coordinates: [-8.4608, 118.7267],
    zoom: 12,
    province: 'Nusa Tenggara Barat',
    type: 'KOTA',
  },
  lombok: {
    name: 'Pulau Lombok',
    coordinates: [-8.5833, 116.3333],
    zoom: 10,
    province: 'Nusa Tenggara Barat',
    type: 'AREA',
  },
  'lombok barat': {
    name: 'Kabupaten Lombok Barat',
    coordinates: [-8.6833, 116.1333],
    zoom: 11,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },
  'lombok tengah': {
    name: 'Kabupaten Lombok Tengah (Mandalika)',
    coordinates: [-8.7000, 116.2833],
    zoom: 11,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },
  mandalika: {
    name: 'Kawasan Mandalika (Lombok)',
    coordinates: [-8.8950, 116.2950],
    zoom: 13,
    province: 'Nusa Tenggara Barat',
    type: 'AREA',
  },
  'lombok timur': {
    name: 'Kabupaten Lombok Timur (Rinjani)',
    coordinates: [-8.6500, 116.5333],
    zoom: 11,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },
  'lombok utara': {
    name: 'Kabupaten Lombok Utara (Gili)',
    coordinates: [-8.3500, 116.2000],
    zoom: 11,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },
  sumbawa: {
    name: 'Kabupaten Sumbawa (Tambora)',
    coordinates: [-8.5000, 117.4333],
    zoom: 10,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },
  dompu: {
    name: 'Kabupaten Dompu',
    coordinates: [-8.5333, 118.4500],
    zoom: 11,
    province: 'Nusa Tenggara Barat',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 17. NUSA TENGGARA TIMUR
  // ==========================================
  'nusa tenggara timur': {
    name: 'Provinsi Nusa Tenggara Timur',
    coordinates: [-8.6574, 121.0794],
    zoom: 8,
    province: 'Nusa Tenggara Timur',
    type: 'PROVINSI',
  },
  ntt: {
    name: 'Provinsi Nusa Tenggara Timur',
    coordinates: [-8.6574, 121.0794],
    zoom: 8,
    province: 'Nusa Tenggara Timur',
    type: 'PROVINSI',
  },
  kupang: {
    name: 'Kota Kupang',
    coordinates: [-10.1772, 123.6070],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  'labuan bajo': {
    name: 'Labuan Bajo (Manggarai Barat)',
    coordinates: [-8.4964, 119.8877],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  'manggarai barat': {
    name: 'Kabupaten Manggarai Barat (Komodo)',
    coordinates: [-8.5500, 120.0000],
    zoom: 10,
    province: 'Nusa Tenggara Timur',
    type: 'KABUPATEN',
  },
  ruteng: {
    name: 'Ruteng (Manggarai)',
    coordinates: [-8.6136, 120.4636],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  ende: {
    name: 'Kabupaten Ende (Kelimutu)',
    coordinates: [-8.8433, 121.6583],
    zoom: 11,
    province: 'Nusa Tenggara Timur',
    type: 'KABUPATEN',
  },
  maumere: {
    name: 'Maumere (Sikka)',
    coordinates: [-8.6199, 122.2111],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  sikka: {
    name: 'Kabupaten Sikka (Maumere)',
    coordinates: [-8.6199, 122.2111],
    zoom: 11,
    province: 'Nusa Tenggara Timur',
    type: 'KABUPATEN',
  },
  larantuka: {
    name: 'Larantuka (Flores Timur/Lewotobi)',
    coordinates: [-8.3411, 122.9839],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  alor: {
    name: 'Kabupaten Alor (Kalabahi)',
    coordinates: [-8.2500, 124.7000],
    zoom: 10,
    province: 'Nusa Tenggara Timur',
    type: 'KABUPATEN',
  },
  sumba: {
    name: 'Pulau Sumba (Waingapu)',
    coordinates: [-9.6667, 120.2667],
    zoom: 9,
    province: 'Nusa Tenggara Timur',
    type: 'AREA',
  },
  waingapu: {
    name: 'Waingapu (Sumba Timur)',
    coordinates: [-9.6558, 120.2639],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },
  atambua: {
    name: 'Atambua (Belu)',
    coordinates: [-9.1067, 124.8925],
    zoom: 12,
    province: 'Nusa Tenggara Timur',
    type: 'KOTA',
  },

  // ==========================================
  // 18. KALIMANTAN BARAT
  // ==========================================
  'kalimantan barat': {
    name: 'Provinsi Kalimantan Barat',
    coordinates: [-0.0263, 109.3425],
    zoom: 8,
    province: 'Kalimantan Barat',
    type: 'PROVINSI',
  },
  kalbar: {
    name: 'Provinsi Kalimantan Barat',
    coordinates: [-0.0263, 109.3425],
    zoom: 8,
    province: 'Kalimantan Barat',
    type: 'PROVINSI',
  },
  pontianak: {
    name: 'Kota Pontianak',
    coordinates: [-0.0263, 109.3425],
    zoom: 12,
    province: 'Kalimantan Barat',
    type: 'KOTA',
  },
  singkawang: {
    name: 'Kota Singkawang',
    coordinates: [0.9067, 108.9867],
    zoom: 12,
    province: 'Kalimantan Barat',
    type: 'KOTA',
  },
  sambas: {
    name: 'Kabupaten Sambas',
    coordinates: [1.3667, 109.3000],
    zoom: 11,
    province: 'Kalimantan Barat',
    type: 'KABUPATEN',
  },
  ketapang: {
    name: 'Kabupaten Ketapang',
    coordinates: [-1.8333, 109.9667],
    zoom: 10,
    province: 'Kalimantan Barat',
    type: 'KABUPATEN',
  },
  sintang: {
    name: 'Kabupaten Sintang',
    coordinates: [0.0667, 111.4833],
    zoom: 10,
    province: 'Kalimantan Barat',
    type: 'KABUPATEN',
  },
  sanggau: {
    name: 'Kabupaten Sanggau',
    coordinates: [0.1167, 110.5833],
    zoom: 11,
    province: 'Kalimantan Barat',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 19. KALIMANTAN TENGAH
  // ==========================================
  'kalimantan tengah': {
    name: 'Provinsi Kalimantan Tengah',
    coordinates: [-1.6815, 113.3824],
    zoom: 8,
    province: 'Kalimantan Tengah',
    type: 'PROVINSI',
  },
  kalteng: {
    name: 'Provinsi Kalimantan Tengah',
    coordinates: [-1.6815, 113.3824],
    zoom: 8,
    province: 'Kalimantan Tengah',
    type: 'PROVINSI',
  },
  palangkaraya: {
    name: 'Kota Palangka Raya',
    coordinates: [-2.2077, 113.9165],
    zoom: 12,
    province: 'Kalimantan Tengah',
    type: 'KOTA',
  },
  'palangka raya': {
    name: 'Kota Palangka Raya',
    coordinates: [-2.2077, 113.9165],
    zoom: 12,
    province: 'Kalimantan Tengah',
    type: 'KOTA',
  },
  sampit: {
    name: 'Sampit (Kotawaringin Timur)',
    coordinates: [-2.5333, 112.9500],
    zoom: 12,
    province: 'Kalimantan Tengah',
    type: 'KOTA',
  },
  'kotawaringin timur': {
    name: 'Kabupaten Kotawaringin Timur',
    coordinates: [-2.5333, 112.9500],
    zoom: 10,
    province: 'Kalimantan Tengah',
    type: 'KABUPATEN',
  },
  'pangkalan bun': {
    name: 'Pangkalan Bun (Kotawaringin Barat)',
    coordinates: [-2.6833, 111.6167],
    zoom: 12,
    province: 'Kalimantan Tengah',
    type: 'KOTA',
  },
  'kotawaringin barat': {
    name: 'Kabupaten Kotawaringin Barat',
    coordinates: [-2.6833, 111.6167],
    zoom: 10,
    province: 'Kalimantan Tengah',
    type: 'KABUPATEN',
  },
  kapuas: {
    name: 'Kabupaten Kapuas (Kuala Kapuas)',
    coordinates: [-3.0094, 114.3853],
    zoom: 11,
    province: 'Kalimantan Tengah',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 20. KALIMANTAN SELATAN
  // ==========================================
  'kalimantan selatan': {
    name: 'Provinsi Kalimantan Selatan',
    coordinates: [-3.0926, 115.2838],
    zoom: 8,
    province: 'Kalimantan Selatan',
    type: 'PROVINSI',
  },
  kalsel: {
    name: 'Provinsi Kalimantan Selatan',
    coordinates: [-3.0926, 115.2838],
    zoom: 8,
    province: 'Kalimantan Selatan',
    type: 'PROVINSI',
  },
  banjarmasin: {
    name: 'Kota Banjarmasin',
    coordinates: [-3.3194, 114.5908],
    zoom: 12,
    province: 'Kalimantan Selatan',
    type: 'KOTA',
  },
  banjarbaru: {
    name: 'Kota Banjarbaru',
    coordinates: [-3.4406, 114.8306],
    zoom: 12,
    province: 'Kalimantan Selatan',
    type: 'KOTA',
  },
  martapura: {
    name: 'Martapura (Kabupaten Banjar)',
    coordinates: [-3.4167, 114.8500],
    zoom: 12,
    province: 'Kalimantan Selatan',
    type: 'KOTA',
  },
  batulicin: {
    name: 'Batulicin (Tanah Bumbu)',
    coordinates: [-3.4500, 115.9833],
    zoom: 12,
    province: 'Kalimantan Selatan',
    type: 'KOTA',
  },
  kotabaru: {
    name: 'Kabupaten Kotabaru',
    coordinates: [-3.2500, 116.2167],
    zoom: 10,
    province: 'Kalimantan Selatan',
    type: 'KABUPATEN',
  },
  tabalong: {
    name: 'Kabupaten Tabalong (Tanjung)',
    coordinates: [-2.1833, 115.3833],
    zoom: 11,
    province: 'Kalimantan Selatan',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 21. KALIMANTAN TIMUR & KALIMANTAN UTARA
  // ==========================================
  'kalimantan timur': {
    name: 'Provinsi Kalimantan Timur',
    coordinates: [0.5387, 116.4194],
    zoom: 8,
    province: 'Kalimantan Timur',
    type: 'PROVINSI',
  },
  kaltim: {
    name: 'Provinsi Kalimantan Timur',
    coordinates: [0.5387, 116.4194],
    zoom: 8,
    province: 'Kalimantan Timur',
    type: 'PROVINSI',
  },
  samarinda: {
    name: 'Kota Samarinda',
    coordinates: [-0.5021, 117.1537],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'KOTA',
  },
  balikpapan: {
    name: 'Kota Balikpapan',
    coordinates: [-1.2379, 116.8529],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'KOTA',
  },
  bontang: {
    name: 'Kota Bontang',
    coordinates: [0.1333, 117.5000],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'KOTA',
  },
  ikn: {
    name: 'Ibu Kota Nusantara (IKN)',
    coordinates: [-0.9634, 116.7088],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'AREA',
  },
  nusantara: {
    name: 'Ibu Kota Nusantara (IKN)',
    coordinates: [-0.9634, 116.7088],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'AREA',
  },
  penajam: {
    name: 'Kabupaten Penajam Paser Utara',
    coordinates: [-1.2833, 116.7500],
    zoom: 11,
    province: 'Kalimantan Timur',
    type: 'KABUPATEN',
  },
  tenggarong: {
    name: 'Tenggarong (Kutai Kartanegara)',
    coordinates: [-0.4333, 116.9833],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'KOTA',
  },
  'kutai kartanegara': {
    name: 'Kabupaten Kutai Kartanegara',
    coordinates: [-0.4333, 116.9833],
    zoom: 10,
    province: 'Kalimantan Timur',
    type: 'KABUPATEN',
  },
  sangatta: {
    name: 'Sangatta (Kutai Timur)',
    coordinates: [0.4833, 117.5667],
    zoom: 12,
    province: 'Kalimantan Timur',
    type: 'KOTA',
  },
  berau: {
    name: 'Kabupaten Berau (Tanjung Redeb/Derawan)',
    coordinates: [2.1500, 117.5000],
    zoom: 10,
    province: 'Kalimantan Timur',
    type: 'KABUPATEN',
  },
  'kalimantan utara': {
    name: 'Provinsi Kalimantan Utara',
    coordinates: [3.0731, 116.0414],
    zoom: 8,
    province: 'Kalimantan Utara',
    type: 'PROVINSI',
  },
  kaltara: {
    name: 'Provinsi Kalimantan Utara',
    coordinates: [3.0731, 116.0414],
    zoom: 8,
    province: 'Kalimantan Utara',
    type: 'PROVINSI',
  },
  tarakan: {
    name: 'Kota Tarakan',
    coordinates: [3.3000, 117.6333],
    zoom: 12,
    province: 'Kalimantan Utara',
    type: 'KOTA',
  },
  'tanjung selor': {
    name: 'Tanjung Selor (Bulungan)',
    coordinates: [2.8333, 117.3667],
    zoom: 12,
    province: 'Kalimantan Utara',
    type: 'KOTA',
  },
  nunukan: {
    name: 'Kabupaten Nunukan (Sebatik)',
    coordinates: [4.1333, 117.6667],
    zoom: 11,
    province: 'Kalimantan Utara',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 22. SULAWESI UTARA & GORONTALO
  // ==========================================
  'sulawesi utara': {
    name: 'Provinsi Sulawesi Utara',
    coordinates: [0.6247, 123.9750],
    zoom: 8,
    province: 'Sulawesi Utara',
    type: 'PROVINSI',
  },
  sulut: {
    name: 'Provinsi Sulawesi Utara',
    coordinates: [0.6247, 123.9750],
    zoom: 8,
    province: 'Sulawesi Utara',
    type: 'PROVINSI',
  },
  manado: {
    name: 'Kota Manado',
    coordinates: [1.4748, 124.8421],
    zoom: 12,
    province: 'Sulawesi Utara',
    type: 'KOTA',
  },
  bitung: {
    name: 'Kota Bitung',
    coordinates: [1.4404, 125.1889],
    zoom: 12,
    province: 'Sulawesi Utara',
    type: 'KOTA',
  },
  tomohon: {
    name: 'Kota Tomohon (Lokon)',
    coordinates: [1.3200, 124.8400],
    zoom: 12,
    province: 'Sulawesi Utara',
    type: 'KOTA',
  },
  kotamobagu: {
    name: 'Kota Kotamobagu',
    coordinates: [0.7306, 124.3144],
    zoom: 12,
    province: 'Sulawesi Utara',
    type: 'KOTA',
  },
  minahasa: {
    name: 'Kabupaten Minahasa (Tondano)',
    coordinates: [1.3000, 124.9167],
    zoom: 11,
    province: 'Sulawesi Utara',
    type: 'KABUPATEN',
  },
  sangihe: {
    name: 'Kepulauan Sangihe (Tahuna/Gunung Ruang)',
    coordinates: [3.6167, 125.5000],
    zoom: 10,
    province: 'Sulawesi Utara',
    type: 'KABUPATEN',
  },
  gorontalo: {
    name: 'Provinsi Gorontalo',
    coordinates: [0.5435, 123.0568],
    zoom: 8,
    province: 'Gorontalo',
    type: 'PROVINSI',
  },
  'kota gorontalo': {
    name: 'Kota Gorontalo',
    coordinates: [0.5435, 123.0568],
    zoom: 12,
    province: 'Gorontalo',
    type: 'KOTA',
  },

  // ==========================================
  // 23. SULAWESI TENGAH & SULAWESI BARAT
  // ==========================================
  'sulawesi tengah': {
    name: 'Provinsi Sulawesi Tengah',
    coordinates: [-1.4300, 121.4456],
    zoom: 8,
    province: 'Sulawesi Tengah',
    type: 'PROVINSI',
  },
  sulteng: {
    name: 'Provinsi Sulawesi Tengah',
    coordinates: [-1.4300, 121.4456],
    zoom: 8,
    province: 'Sulawesi Tengah',
    type: 'PROVINSI',
  },
  palu: {
    name: 'Kota Palu (Sesar Palu-Koro)',
    coordinates: [-0.8917, 119.8707],
    zoom: 12,
    province: 'Sulawesi Tengah',
    type: 'KOTA',
  },
  poso: {
    name: 'Kabupaten Poso',
    coordinates: [-1.3958, 120.7528],
    zoom: 11,
    province: 'Sulawesi Tengah',
    type: 'KABUPATEN',
  },
  morowali: {
    name: 'Kabupaten Morowali (Bahodopi)',
    coordinates: [-2.6500, 121.9000],
    zoom: 10,
    province: 'Sulawesi Tengah',
    type: 'KABUPATEN',
  },
  luwuk: {
    name: 'Kota Luwuk (Banggai)',
    coordinates: [-0.9517, 122.7875],
    zoom: 12,
    province: 'Sulawesi Tengah',
    type: 'KOTA',
  },
  tolitoli: {
    name: 'Kabupaten Tolitoli',
    coordinates: [1.0333, 120.8167],
    zoom: 11,
    province: 'Sulawesi Tengah',
    type: 'KABUPATEN',
  },
  'sulawesi barat': {
    name: 'Provinsi Sulawesi Barat',
    coordinates: [-2.8441, 119.2321],
    zoom: 8,
    province: 'Sulawesi Barat',
    type: 'PROVINSI',
  },
  sulbar: {
    name: 'Provinsi Sulawesi Barat',
    coordinates: [-2.8441, 119.2321],
    zoom: 8,
    province: 'Sulawesi Barat',
    type: 'PROVINSI',
  },
  mamuju: {
    name: 'Kota Mamuju',
    coordinates: [-2.6748, 118.8885],
    zoom: 12,
    province: 'Sulawesi Barat',
    type: 'KOTA',
  },
  'polewali mandar': {
    name: 'Kabupaten Polewali Mandar (Polman)',
    coordinates: [-3.4333, 119.3333],
    zoom: 11,
    province: 'Sulawesi Barat',
    type: 'KABUPATEN',
  },
  polman: {
    name: 'Polewali Mandar (Polman)',
    coordinates: [-3.4333, 119.3333],
    zoom: 12,
    province: 'Sulawesi Barat',
    type: 'KOTA',
  },

  // ==========================================
  // 24. SULAWESI SELATAN & SULAWESI TENGGARA
  // ==========================================
  'sulawesi selatan': {
    name: 'Provinsi Sulawesi Selatan',
    coordinates: [-3.6687, 119.9740],
    zoom: 8,
    province: 'Sulawesi Selatan',
    type: 'PROVINSI',
  },
  sulsel: {
    name: 'Provinsi Sulawesi Selatan',
    coordinates: [-3.6687, 119.9740],
    zoom: 8,
    province: 'Sulawesi Selatan',
    type: 'PROVINSI',
  },
  makassar: {
    name: 'Kota Makassar',
    coordinates: [-5.1477, 119.4327],
    zoom: 12,
    province: 'Sulawesi Selatan',
    type: 'KOTA',
  },
  parepare: {
    name: 'Kota Parepare',
    coordinates: [-4.0131, 119.6256],
    zoom: 12,
    province: 'Sulawesi Selatan',
    type: 'KOTA',
  },
  palopo: {
    name: 'Kota Palopo',
    coordinates: [-2.9944, 120.1969],
    zoom: 12,
    province: 'Sulawesi Selatan',
    type: 'KOTA',
  },
  gowa: {
    name: 'Kabupaten Gowa (Sungguminasa)',
    coordinates: [-5.2000, 119.4500],
    zoom: 11,
    province: 'Sulawesi Selatan',
    type: 'KABUPATEN',
  },
  maros: {
    name: 'Kabupaten Maros (Bantimurung)',
    coordinates: [-5.0000, 119.5667],
    zoom: 11,
    province: 'Sulawesi Selatan',
    type: 'KABUPATEN',
  },
  bone: {
    name: 'Kabupaten Bone (Watampone)',
    coordinates: [-4.5386, 120.3283],
    zoom: 11,
    province: 'Sulawesi Selatan',
    type: 'KABUPATEN',
  },
  bulukumba: {
    name: 'Kabupaten Bulukumba (Tanjung Bira)',
    coordinates: [-5.5500, 120.1833],
    zoom: 11,
    province: 'Sulawesi Selatan',
    type: 'KABUPATEN',
  },
  toraja: {
    name: 'Tana Toraja & Toraja Utara',
    coordinates: [-3.0983, 119.8633],
    zoom: 11,
    province: 'Sulawesi Selatan',
    type: 'AREA',
  },
  rantepao: {
    name: 'Rantepao (Toraja Utara)',
    coordinates: [-2.9711, 119.9000],
    zoom: 12,
    province: 'Sulawesi Selatan',
    type: 'KOTA',
  },
  'sulawesi tenggara': {
    name: 'Provinsi Sulawesi Tenggara',
    coordinates: [-4.1449, 122.1746],
    zoom: 8,
    province: 'Sulawesi Tenggara',
    type: 'PROVINSI',
  },
  sultra: {
    name: 'Provinsi Sulawesi Tenggara',
    coordinates: [-4.1449, 122.1746],
    zoom: 8,
    province: 'Sulawesi Tenggara',
    type: 'PROVINSI',
  },
  kendari: {
    name: 'Kota Kendari',
    coordinates: [-3.9985, 122.5126],
    zoom: 12,
    province: 'Sulawesi Tenggara',
    type: 'KOTA',
  },
  baubau: {
    name: 'Kota Baubau (Pulau Buton)',
    coordinates: [-5.4636, 122.6022],
    zoom: 12,
    province: 'Sulawesi Tenggara',
    type: 'KOTA',
  },
  kolaka: {
    name: 'Kabupaten Kolaka',
    coordinates: [-4.0500, 121.6000],
    zoom: 11,
    province: 'Sulawesi Tenggara',
    type: 'KABUPATEN',
  },
  wakatobi: {
    name: 'Kepulauan Wakatobi (Wangi-Wangi)',
    coordinates: [-5.3167, 123.5833],
    zoom: 10,
    province: 'Sulawesi Tenggara',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 25. MALUKU & MALUKU UTARA
  // ==========================================
  maluku: {
    name: 'Provinsi Maluku',
    coordinates: [-3.2385, 130.1453],
    zoom: 7,
    province: 'Maluku',
    type: 'PROVINSI',
  },
  ambon: {
    name: 'Kota Ambon',
    coordinates: [-3.6547, 128.1906],
    zoom: 12,
    province: 'Maluku',
    type: 'KOTA',
  },
  tual: {
    name: 'Kota Tual (Kepulauan Kei)',
    coordinates: [-5.6333, 132.7500],
    zoom: 12,
    province: 'Maluku',
    type: 'KOTA',
  },
  'maluku tengah': {
    name: 'Kabupaten Maluku Tengah (Masohi)',
    coordinates: [-3.3000, 128.9667],
    zoom: 9,
    province: 'Maluku',
    type: 'KABUPATEN',
  },
  'banda neira': {
    name: 'Kepulauan Banda (Banda Neira)',
    coordinates: [-4.5244, 129.9042],
    zoom: 12,
    province: 'Maluku',
    type: 'AREA',
  },
  seram: {
    name: 'Pulau Seram',
    coordinates: [-3.1333, 129.5000],
    zoom: 9,
    province: 'Maluku',
    type: 'AREA',
  },
  buru: {
    name: 'Pulau Buru (Namlea)',
    coordinates: [-3.4000, 126.7000],
    zoom: 9,
    province: 'Maluku',
    type: 'AREA',
  },
  'maluku utara': {
    name: 'Provinsi Maluku Utara',
    coordinates: [1.5709, 127.8088],
    zoom: 8,
    province: 'Maluku Utara',
    type: 'PROVINSI',
  },
  malut: {
    name: 'Provinsi Maluku Utara',
    coordinates: [1.5709, 127.8088],
    zoom: 8,
    province: 'Maluku Utara',
    type: 'PROVINSI',
  },
  ternate: {
    name: 'Kota Ternate (Gunung Gamalama)',
    coordinates: [0.7903, 127.3639],
    zoom: 12,
    province: 'Maluku Utara',
    type: 'KOTA',
  },
  tidore: {
    name: 'Kota Tidore Kepulauan',
    coordinates: [0.6833, 127.4000],
    zoom: 12,
    province: 'Maluku Utara',
    type: 'KOTA',
  },
  sofifi: {
    name: 'Sofifi (Ibukota Maluku Utara)',
    coordinates: [0.7333, 127.5667],
    zoom: 12,
    province: 'Maluku Utara',
    type: 'KOTA',
  },
  halmahera: {
    name: 'Pulau Halmahera (Gunung Ibu)',
    coordinates: [1.0000, 128.0000],
    zoom: 8,
    province: 'Maluku Utara',
    type: 'AREA',
  },
  morotai: {
    name: 'Pulau Morotai',
    coordinates: [2.3333, 128.4167],
    zoom: 10,
    province: 'Maluku Utara',
    type: 'KABUPATEN',
  },

  // ==========================================
  // 26. SELURUH 6 PROVINSI DI TANAH PAPUA
  // ==========================================
  papua: {
    name: 'Provinsi Papua',
    coordinates: [-2.5916, 140.6690],
    zoom: 8,
    province: 'Papua',
    type: 'PROVINSI',
  },
  jayapura: {
    name: 'Kota Jayapura',
    coordinates: [-2.5916, 140.6690],
    zoom: 12,
    province: 'Papua',
    type: 'KOTA',
  },
  sentani: {
    name: 'Sentani (Kabupaten Jayapura)',
    coordinates: [-2.5667, 140.5167],
    zoom: 12,
    province: 'Papua',
    type: 'KOTA',
  },
  biak: {
    name: 'Biak Numfor',
    coordinates: [-1.0167, 136.0833],
    zoom: 11,
    province: 'Papua',
    type: 'KABUPATEN',
  },
  serui: {
    name: 'Serui (Kepulauan Yapen)',
    coordinates: [-1.8833, 136.2333],
    zoom: 12,
    province: 'Papua',
    type: 'KOTA',
  },
  'papua barat': {
    name: 'Provinsi Papua Barat',
    coordinates: [-1.3361, 133.1747],
    zoom: 8,
    province: 'Papua Barat',
    type: 'PROVINSI',
  },
  manokwari: {
    name: 'Kota Manokwari',
    coordinates: [-0.8615, 134.0620],
    zoom: 12,
    province: 'Papua Barat',
    type: 'KOTA',
  },
  fakfak: {
    name: 'Kabupaten Fakfak',
    coordinates: [-2.9264, 132.2961],
    zoom: 11,
    province: 'Papua Barat',
    type: 'KABUPATEN',
  },
  kaimana: {
    name: 'Kabupaten Kaimana',
    coordinates: [-3.6667, 133.7667],
    zoom: 11,
    province: 'Papua Barat',
    type: 'KABUPATEN',
  },
  'papua barat daya': {
    name: 'Provinsi Papua Barat Daya',
    coordinates: [-0.8762, 131.2558],
    zoom: 8,
    province: 'Papua Barat Daya',
    type: 'PROVINSI',
  },
  sorong: {
    name: 'Kota Sorong',
    coordinates: [-0.8762, 131.2558],
    zoom: 12,
    province: 'Papua Barat Daya',
    type: 'KOTA',
  },
  'raja ampat': {
    name: 'Kepulauan Raja Ampat (Waisai)',
    coordinates: [-0.4333, 130.8167],
    zoom: 10,
    province: 'Papua Barat Daya',
    type: 'KABUPATEN',
  },
  'papua tengah': {
    name: 'Provinsi Papua Tengah',
    coordinates: [-3.8000, 136.0000],
    zoom: 8,
    province: 'Papua Tengah',
    type: 'PROVINSI',
  },
  nabire: {
    name: 'Kota Nabire',
    coordinates: [-3.3667, 135.5000],
    zoom: 12,
    province: 'Papua Tengah',
    type: 'KOTA',
  },
  timika: {
    name: 'Kota Timika (Mimika)',
    coordinates: [-4.5467, 136.8837],
    zoom: 12,
    province: 'Papua Tengah',
    type: 'KOTA',
  },
  mimika: {
    name: 'Kabupaten Mimika (Timika/Grasberg)',
    coordinates: [-4.5467, 136.8837],
    zoom: 10,
    province: 'Papua Tengah',
    type: 'KABUPATEN',
  },
  'papua pegunungan': {
    name: 'Provinsi Papua Pegunungan',
    coordinates: [-4.0954, 138.9442],
    zoom: 8,
    province: 'Papua Pegunungan',
    type: 'PROVINSI',
  },
  wamena: {
    name: 'Kota Wamena (Jayawijaya)',
    coordinates: [-4.0954, 138.9442],
    zoom: 12,
    province: 'Papua Pegunungan',
    type: 'KOTA',
  },
  jayawijaya: {
    name: 'Kabupaten Jayawijaya (Lembah Baliem)',
    coordinates: [-4.0954, 138.9442],
    zoom: 10,
    province: 'Papua Pegunungan',
    type: 'KABUPATEN',
  },
  'papua selatan': {
    name: 'Provinsi Papua Selatan',
    coordinates: [-8.4991, 140.4011],
    zoom: 8,
    province: 'Papua Selatan',
    type: 'PROVINSI',
  },
  merauke: {
    name: 'Kota Merauke',
    coordinates: [-8.4991, 140.4011],
    zoom: 12,
    province: 'Papua Selatan',
    type: 'KOTA',
  },
  'boven digoel': {
    name: 'Kabupaten Boven Digoel (Tanah Merah)',
    coordinates: [-5.7500, 140.3000],
    zoom: 10,
    province: 'Papua Selatan',
    type: 'KABUPATEN',
  },
  asmat: {
    name: 'Kabupaten Asmat (Agats)',
    coordinates: [-5.5333, 138.1333],
    zoom: 10,
    province: 'Papua Selatan',
    type: 'KABUPATEN',
  },
};

/**
 * Searches the location dictionary for a match based on a user's raw query or parsed location name.
 */
export function findLocationInfo(query: string): LocationInfo | null {
  if (!query) return null;
  const q = query.toLowerCase().trim();

  // Strip prefixes like "kota ", "kabupaten ", "kab. ", "kab ", "provinsi ", "prov. ", "pulau "
  const cleaned = q
    .replace(/^(kota|kabupaten|kab\.?|provinsi|prov\.?|pulau)\s+/i, '')
    .trim();

  // 1. Direct match with cleaned or raw query
  if (INDONESIA_LOCATIONS[cleaned]) {
    return INDONESIA_LOCATIONS[cleaned];
  }
  if (INDONESIA_LOCATIONS[q]) {
    return INDONESIA_LOCATIONS[q];
  }

  // 2. Word boundary match across keys (sorted by length descending)
  // Ensures "balikpapan" will NOT match "bali", "banda aceh" matches before "aceh"
  const sortedKeys = Object.keys(INDONESIA_LOCATIONS).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`(^|\\s|[^a-zA-Z0-9])${escaped}($|\\s|[^a-zA-Z0-9])`, 'i');
    if (regex.test(cleaned) || regex.test(q)) {
      return INDONESIA_LOCATIONS[key];
    }
  }

  // 3. Fallback: match against location.name or location.province
  for (const info of Object.values(INDONESIA_LOCATIONS)) {
    const nameClean = info.name.toLowerCase();
    const escapedCleaned = cleaned.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`(^|\\s|[^a-zA-Z0-9])${escapedCleaned}($|\\s|[^a-zA-Z0-9])`, 'i');
    if (regex.test(nameClean)) {
      return info;
    }
  }

  return null;
}
