import { SafetyEvent } from '@/types/safety';

export const CURATED_INCIDENTS: SafetyEvent[] = [
  // --- BANDUNG DISASTER & FLOOD MEMORY (BNPB / DIBI / BPBD) ---
  {
    id: 'inc-bdg-flood-2026-09',
    fingerprint: 'flood-dayeuhkolot-2026-09-18',
    title: 'Banjir Luapan Sungai Citarum & Cipalasari Dayeuhkolot',
    description: 'Hujan deras berdurasi > 4 jam di wilayah hulu Bandung Selatan menyebabkan Sungai Citarum meluap. Ketinggian muka air berkisar 40 - 120 cm merendam pemukiman warga Desa Dayeuhkolot dan akses jalan utama penghubung Bandung - Banjaran.',
    category: 'FLOOD',
    subcategory: 'LUAPAN_SUNGAI',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'BPBD Kabupaten Bandung & Pusdalops Jabar',
    sourceUrl: 'https://bpbd.jabarprov.go.id/',
    latitude: -7.0019,
    longitude: 107.6205,
    locationName: 'Kecamatan Dayeuhkolot, Bandung Selatan',
    district: 'Dayeuhkolot',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-09-18T14:30:00Z',
    ingestedAt: '2026-09-18T15:10:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: '1.240 KK terdampak, Jalan Raya Dayeuhkolot terputus sementara',
    metadata: {
      waterLevelCm: 120,
      affectedHouseholds: 1240,
      riverBasin: 'DAS Citarum Hulu',
    },
  },
  {
    id: 'inc-bdg-flood-baleendah-2026',
    fingerprint: 'flood-baleendah-andir-2026-08',
    title: 'Banjir Genangan Kelurahan Andir & Baleendah',
    description: 'Genangan air berulang merendam pemukiman Kampung Cieunteung dan Kelurahan Andir dengan ketinggian air 30 - 80 cm setelah hujan intensitas tinggi di wilayah Cekungan Bandung.',
    category: 'FLOOD',
    subcategory: 'GENANGAN_KRONIS',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BNPB DIBI & BPBD Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.9961,
    longitude: 107.6322,
    locationName: 'Kampung Cieunteung, Baleendah',
    district: 'Baleendah',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-08-25T17:00:00Z',
    ingestedAt: '2026-08-26T08:00:00Z',
    periodLabel: 'Agu 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: '850 rumah tergenang, pompa polder Cieunteung dioperasikan maksimal',
    metadata: {
      waterLevelCm: 80,
      polderStatus: 'Operasional',
    },
  },
  {
    id: 'inc-bdg-pasteur-flashflood',
    fingerprint: 'flood-pasteur-dr-djundjunan-2026-03',
    title: 'Banjir Cileuncang Simpang Pasteur - Jl. Dr. Djundjunan Kota Bandung',
    description: 'Luapan Sungai Citepus saat hujan ekstrem mengakibatkan genangan setinggi 50 cm di depan Mall BTC Pasteur, memicu kemacetan parah keluar masuk Gerbang Tol Pasteur.',
    category: 'FLOOD',
    subcategory: 'CILEUNCANG_DRAINASE',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Diskar PB Kota Bandung & Dishub Bandung',
    sourceUrl: 'https://diskarpb.bandung.go.id/',
    latitude: -6.8967,
    longitude: 107.5855,
    locationName: 'Jl. Dr. Djundjunan (Pasteur), Sukajadi',
    district: 'Sukajadi',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-03-12T16:15:00Z',
    ingestedAt: '2026-03-12T18:00:00Z',
    periodLabel: 'Mar 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Lalu lintas Tol Pasteur lumpuh 3 jam, belasan kendaraan roda dua mogok',
    metadata: {
      drainageIssue: 'Penyempitan gorong-gorong Citepus',
    },
  },
  {
    id: 'inc-bdg-gedebage-flood',
    fingerprint: 'flood-gedebage-soetta-2026-01',
    title: 'Genangan Banjir Arteri Gedebage & Pasar Induk Kota Bandung',
    description: 'Hujan lebat berjam-jam menyebabkan air antrean di saluran Sungai Cinambo meluap ke Jalan Soekarno-Hatta depan Pasar Induk Gedebage.',
    category: 'FLOOD',
    subcategory: 'GENANGAN_JALAN',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BPBD Kota Bandung & Dinas SDA Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.9482,
    longitude: 107.6841,
    locationName: 'Kawasan Pasar Induk Gedebage, Soekarno-Hatta',
    district: 'Gedebage',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-01-20T18:40:00Z',
    ingestedAt: '2026-01-21T09:00:00Z',
    periodLabel: 'Jan 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Jalan Soekarno-Hatta tergenang 40 cm sepanjang 300 meter',
    metadata: {},
  },

  // --- TRAFFIC & ROAD ACCIDENTS (KORLANTAS / KNKT / JASA MARGA) ---
  {
    id: 'inc-traffic-cipularang-km92',
    fingerprint: 'traffic-tol-cipularang-km92-2026-09',
    title: 'Kecelakaan Beruntun Tol Cipularang KM 92 Arah Jakarta',
    description: 'Truk muatan berat mengalami kegagalan fungsi pengereman (rem blong) pada turunan tajam Tol Cipularang KM 92, menabrak beruntun 11 kendaraan roda empat yang sedang melambat karena kepadatan lalu lintas.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_BERUNTUN_TOL',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PJR Korlantas Polri & Jasa Marga Traffic Information',
    sourceUrl: 'https://jasamarga.com/',
    latitude: -6.6432,
    longitude: 107.4121,
    locationName: 'Ruas Jalan Tol Cipularang KM 92 (Purwakarta - Bandung)',
    district: 'Sukatani',
    regencyCity: 'Kabupaten Purwakarta / Koridor Bandung Raya',
    province: 'Jawa Barat',
    occurredAt: '2026-09-08T15:20:00Z',
    ingestedAt: '2026-09-08T16:05:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 1,
    casualtiesInjured: 14,
    impactSummary: 'Tol Cipularang ditutup arah Jakarta selama 4 jam, 12 kendaraan rusak berat',
    metadata: {
      investigationBody: 'KNKT & Korlantas Polri',
      causeFactor: 'Rem blong pada kontur turunan terjal',
      vehicleTypes: ['Truk Kontainer', 'Minibus', 'Sedan'],
    },
  },
  {
    id: 'inc-traffic-soetta-bandung-2026',
    fingerprint: 'traffic-soetta-mohammad-toha-2026-09',
    title: 'Kecelakaan Fatal Jalur Arteri Soekarno-Hatta - Moh. Toha Bandung',
    description: 'Truk tangki menabrak separator jalan dan dua sepeda motor di perempatan by-pass Jl. Soekarno-Hatta persimpangan Moh. Toha saat cuaca hujan gerimis.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_LALU_LINTAS_KOTA',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'Satlantas Polrestabes Bandung & Dishub Kota Bandung',
    sourceUrl: 'https://korlantas.polri.go.id/',
    latitude: -6.9538,
    longitude: 107.6119,
    locationName: 'Simpang Empat By-pass Soekarno Hatta - Moh Toha',
    district: 'Regol',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-09-19T07:15:00Z',
    ingestedAt: '2026-09-19T08:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 2,
    casualtiesInjured: 3,
    impactSummary: 'Kemacetan panjang 4 km di jalur cepat Soekarno-Hatta arah barat',
    metadata: {
      roadType: 'Jalan Nasional Arteri Primer',
      weatherCondition: 'Hujan Gerimis / Jalan Licin',
    },
  },
  {
    id: 'inc-traffic-nagreg-2026',
    fingerprint: 'traffic-jalur-nagreg-leles-2026-04',
    title: 'Kecelakaan Tunggal Truk Terguling Tanjakan Nagreg',
    description: 'Truk pengangkut semen gagal menanjak di tikungan tajam Jalur Lingkar Nagreg akibat muatan berlebih (ODOL), lalu mundur dan terbalik menutup 2 lajur jalan.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KECELAKAAN_TUNGGAL_ODOL',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Korlantas Polri via BPS & Dishub Jabar',
    sourceUrl: 'https://jabar.bps.go.id/',
    latitude: -7.0261,
    longitude: 107.8932,
    locationName: 'Jalur Lingkar Nagreg KM 37',
    district: 'Nagreg',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-04-14T05:30:00Z',
    ingestedAt: '2026-04-14T07:00:00Z',
    periodLabel: 'Apr 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 1,
    impactSummary: 'Jalur utama Bandung - Garut/Tasikmalaya dialihkan ke jalur lama',
    metadata: {
      overdimensionOverload: true,
    },
  },
  {
    id: 'inc-traffic-padaleunyi-km149',
    fingerprint: 'traffic-padaleunyi-km149-gedebage-2026-07',
    title: 'Insiden Tabrakan Beruntun 4 Mobil Tol Padaleunyi KM 149 Gedebage',
    description: 'Pengereman mendadak kendaraan di lajur cepat saat mendekati exit tol KM 149 Gedebage menyebabkan tabrakan karambol 4 minibus.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_JALUR_CEPAT_TOL',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Jasa Marga Traffic Monitoring & PJR Jabar',
    sourceUrl: 'https://jasamarga.com/',
    latitude: -6.9582,
    longitude: 107.6953,
    locationName: 'Jalan Tol Padaleunyi KM 149 (Dekat Stasiun KCIC Tegalluar)',
    district: 'Gedebage',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-07-28T11:45:00Z',
    ingestedAt: '2026-07-28T12:30:00Z',
    periodLabel: 'Jul 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 4,
    impactSummary: 'Lajur cepat tersendat 45 menit sebelum kendaraan dievakuasi ke bahu jalan',
    metadata: {},
  },

  // --- TRANSPORTATION ACCIDENT (KNKT INVESTIGATION) ---
  {
    id: 'inc-rail-cicalengka-knkt',
    fingerprint: 'knkt-ka-turangga-commuter-cicalengka',
    title: 'Kecelakaan Tabrakan Kereta Api KA Turangga vs KA Lokal Baraya',
    description: 'Tabrakan adu banteng (head-on collision) antara KA 65A Turangga relasi Surabaya-Bandung dan KA 350 Commuter Line Bandung Raya di petak jalan Cicalengka - Haurpugur KM 181.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KECELAKAAN_PERKERETAAPIAN',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'KNKT (Laporan Investigasi No. KNKT.24.01.01.01) & Kemenhub',
    sourceUrl: 'https://knkt.dephub.go.id/',
    latitude: -6.9789,
    longitude: 107.8242,
    locationName: 'Petak Jalan KM 181+700 Cicalengka - Haurpugur',
    district: 'Cicalengka',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2024-01-05T06:03:00Z',
    ingestedAt: '2024-01-05T08:00:00Z',
    periodLabel: 'Jan 2024',
    casualtiesFatal: 4,
    casualtiesInjured: 37,
    impactSummary: 'Jalur selatan lumpuh total 24 jam, lokomotif CC206 & CC201 rusak parah',
    metadata: {
      agency: 'Komite Nasional Keselamatan Transportasi (KNKT)',
      reportCode: 'KNKT.24.01.01.01',
      factor: 'Anomali transmisi data uncommanded blok mekanik ke elektrik',
    },
  },

  // --- SEISMIC ACTIVITY & FAULTS (BMKG & PVMBG) ---
  {
    id: 'inc-earthquake-lembang-garsela',
    fingerprint: 'quake-sesar-garsela-kab-bandung-2024-09',
    title: 'Gempa Bumi Dangkal M 5.0 Akibat Sesar Garsela Mengguncang Kertasari Bandung',
    description: 'Gempa tektonik darat dangkal kedalaman 10 km dipicu oleh deformasi batuan pada zona Sesar Garsela (Garut Selatan). Guncangan mencapai intensitas IV-V MMI di Kertasari dan Pangalengan, dirasakan nyata di Kota Bandung.',
    category: 'EARTHQUAKE',
    subcategory: 'SESAR_AKTIF_DARAT',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Pusat Gempa Bumi & Tsunami BMKG',
    sourceUrl: 'https://bmkg.go.id/',
    latitude: -7.1902,
    longitude: 107.6712,
    locationName: 'Kecamatan Kertasari & Bedeng, Kabupaten Bandung',
    district: 'Kertasari',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2024-09-18T09:41:00Z',
    ingestedAt: '2024-09-18T10:00:00Z',
    periodLabel: 'Sep 2024',
    casualtiesFatal: 2,
    casualtiesInjured: 81,
    impactSummary: '4.483 bangunan rumah & fasilitas publik di Kertasari dan Pangalengan rusak',
    metadata: {
      magnitude: 5.0,
      depth: '10 km',
      faultSystem: 'Sesar Garsela (Segmen Rakutai)',
      mmiScale: 'V MMI Kertasari, III MMI Kota Bandung',
    },
  },

  // --- VOLCANIC ACTIVITY (PVMBG BULLETIN) ---
  {
    id: 'inc-volcano-tangkuban-parahu',
    fingerprint: 'volcano-tangkuban-parahu-level2-waspada',
    title: 'Aktivitas Gunung Api Tangkuban Parahu: Status Level II (Waspada)',
    description: 'Pusat Vulkanologi dan Mitigasi Bencana Geologi (PVMBG) menetapkan Status Waspada seiring peningkatan gempa hembusan dan emisi gas CO2 di Kawah Ratu. Masyarakat dilarang mendekati bibir kawah dalam radius 500 meter.',
    category: 'VOLCANO',
    subcategory: 'STATUS_GUNUNG_API',
    severity: 'MEDIUM',
    status: 'MONITORING',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PVMBG Badan Geologi Kementerian ESDM (MAGMA Indonesia)',
    sourceUrl: 'https://magma.esdm.go.id/',
    latitude: -6.7594,
    longitude: 107.6097,
    locationName: 'Kawah Ratu Gunung Tangkuban Parahu (Lembang - Subang)',
    district: 'Lembang',
    regencyCity: 'Kabupaten Bandung Barat',
    province: 'Jawa Barat',
    occurredAt: '2026-09-15T08:00:00Z',
    ingestedAt: '2026-09-15T09:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Radius rekomendasi bahaya 500 meter dari Kawah Ratu & Kawah Upas',
    metadata: {
      alertLevel: 'Level II (Waspada)',
      crater: 'Kawah Ratu',
      hazardRadiusMeters: 500,
    },
  },
  {
    id: 'inc-volcano-ruang-erupsi',
    fingerprint: 'volcano-ruang-level4-awas-erupsi',
    title: 'Erupsi Eksplosif Gunung Ruang Sulawesi Utara: Status Level IV (Awas)',
    description: 'Letusan kolom abu vulkanik mencapai ketinggian 3.000 meter di atas puncak. PVMBG menaikkan status ke Level IV (Awas) disertai ancaman lontaran batu pijar dan potensi gelombang tsunami akibat runtuhan material ke laut.',
    category: 'VOLCANO',
    subcategory: 'ERUPSI_EKSPLOSIF',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PVMBG - Badan Geologi & BNPB',
    sourceUrl: 'https://magma.esdm.go.id/',
    latitude: 2.3031,
    longitude: 125.3703,
    locationName: 'Pulau Ruang, Kabupaten Sitaro',
    district: 'Tagulandang',
    regencyCity: 'Kabupaten Kepulauan Siau Tagulandang Biaro',
    province: 'Sulawesi Utara',
    occurredAt: '2026-09-21T18:15:00Z',
    ingestedAt: '2026-09-22T06:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Evakuasi total seluruh penduduk Pulau Ruang radius bahaya 6 km',
    metadata: {
      alertLevel: 'Level IV (Awas)',
      columnHeightMeters: 3000,
      vonaNotice: 'RED',
    },
  },

  // --- INDUSTRIAL & ENVIRONMENTAL HAZARDS ---
  {
    id: 'inc-industrial-balongan-fire',
    fingerprint: 'industrial-kilang-balongan-pertamina',
    title: 'Insiden Kebakaran Tangki T-301 Kilang Minyak Balongan Pertamina',
    description: 'Ledakan dan kobaran api hebat membakar 4 tangki penyimpanan BBM kilang minyak RU VI Balongan Indramayu saat terjadi hujan deras disertai petir hebat.',
    category: 'INDUSTRIAL_ACCIDENT',
    subcategory: 'KEBAKARAN_KILANG_MIGAS',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Ditjen Migas ESDM & BPBD Indramayu',
    sourceUrl: 'https://migas.esdm.go.id/',
    latitude: -6.3683,
    longitude: 108.3842,
    locationName: 'Kilang Pertamina RU VI Balongan',
    district: 'Balongan',
    regencyCity: 'Kabupaten Indramayu',
    province: 'Jawa Barat',
    occurredAt: '2021-03-29T00:45:00Z',
    ingestedAt: '2021-03-29T03:00:00Z',
    periodLabel: 'Mar 2021',
    casualtiesFatal: 1,
    casualtiesInjured: 29,
    impactSummary: '1.000 warga diungsikan, pasokan BBM regional sempat dialihkan',
    metadata: {
      facilityType: 'Refinery Unit Oil & Gas Storage',
      causeFactor: 'Sambaran kilat petir saat cuaca ekstrem',
    },
  },
  {
    id: 'inc-industrial-cimahi-textile',
    fingerprint: 'industrial-pabrik-tekstil-cimahi-2026-06',
    title: 'Kebakaran Gudang Bahan Kimia & Kain Industri Tekstil Cimahi',
    description: 'Konsleting pada panel trafo listrik utama menyulut kobaran api di gudang penyimpanan zat pewarna tekstil di Kawasan Industri Cimahi Selatan.',
    category: 'INDUSTRIAL_ACCIDENT',
    subcategory: 'KEBAKARAN_PABRIK',
    severity: 'HIGH',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Damkar Kota Cimahi & Diskar PB Bandung',
    sourceUrl: 'https://cimahikota.go.id/',
    latitude: -6.8978,
    longitude: 107.5389,
    locationName: 'Kawasan Industri Cimahi Selatan (Batas Kota Bandung)',
    district: 'Cimahi Selatan',
    regencyCity: 'Kota Cimahi / Bandung Raya',
    province: 'Jawa Barat',
    occurredAt: '2026-06-19T21:10:00Z',
    ingestedAt: '2026-06-20T08:00:00Z',
    periodLabel: 'Jun 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 2,
    impactSummary: '12 armada damkar dikerahkan, kerugian ditaksir Rp 3,2 Miliar',
    metadata: {},
  },
  {
    id: 'inc-landslide-cisarua-lembang',
    fingerprint: 'landslide-kolonel-masturi-cisarua-2026-02',
    title: 'Bencana Tanah Longsor Tebing Jl. Kolonel Masturi Lembang',
    description: 'Tebing setinggi 25 meter mengalami longsor akibat erosi hujan lebat menutup total badan Jalan Kolonel Masturi penghubung Cimahi - Lembang Bandung Barat.',
    category: 'LANDSLIDE',
    subcategory: 'LONGSOR_TEBING_JALAN',
    severity: 'HIGH',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BPBD Kabupaten Bandung Barat & Dinas Bina Marga Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.8213,
    longitude: 107.5768,
    locationName: 'Jalan Kolonel Masturi KM 4, Cisarua',
    district: 'Cisarua',
    regencyCity: 'Kabupaten Bandung Barat',
    province: 'Jawa Barat',
    occurredAt: '2026-02-17T19:30:00Z',
    ingestedAt: '2026-02-18T07:00:00Z',
    periodLabel: 'Feb 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 1,
    impactSummary: 'Jalan tertutup material longsor 15 meter, akses wisata dialihkan',
    metadata: {},
  },
];
