import { SafetyEvent } from '@/types/safety';

export const CURATED_INCIDENTS: SafetyEvent[] = [
  // --- BANDUNG DISASTER & FLOOD MEMORY (BNPB / DIBI / BPBD) ---
  {
    id: 'inc-bdg-flood-2026-09',
    fingerprint: 'flood-dayeuhkolot-2026-09-18',
    title: 'Banjir Luapan Sungai Citarum & Cipalasari Dayeuhkolot',
    description: 'Hujan deras berdurasi > 4 jam di wilayah hulu Bandung Selatan menyebabkan Sungai Citarum meluap. Ketinggian muka air berkisar 40 - 120 cm merendam pemukiman warga Desa Dayeuhkolot dan akses jalan utama penghubung Bandung - Banjaran.',
    category: 'FLOOD',
    subcategory: 'LUAPAN_SUNGAI',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'BPBD Kabupaten Bandung & Pusdalops Jabar',
    sourceUrl: 'https://bpbd.jabarprov.go.id/',
    latitude: -7.0019,
    longitude: 107.6205,
    locationName: 'Kecamatan Dayeuhkolot, Bandung Selatan',
    district: 'Dayeuhkolot',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-09-18T14:30:00Z',
    ingestedAt: '2026-09-18T15:10:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: '1.240 KK terdampak, Jalan Raya Dayeuhkolot terputus sementara',
    metadata: {
      waterLevelCm: 120,
      affectedHouseholds: 1240,
      riverBasin: 'DAS Citarum Hulu',
    },
  },
  {
    id: 'inc-bdg-flood-baleendah-2026',
    fingerprint: 'flood-baleendah-andir-2026-08',
    title: 'Banjir Genangan Kelurahan Andir & Baleendah',
    description: 'Genangan air berulang merendam pemukiman Kampung Cieunteung dan Kelurahan Andir dengan ketinggian air 30 - 80 cm setelah hujan intensitas tinggi di wilayah Cekungan Bandung.',
    category: 'FLOOD',
    subcategory: 'GENANGAN_KRONIS',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BNPB DIBI & BPBD Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.9961,
    longitude: 107.6322,
    locationName: 'Kampung Cieunteung, Baleendah',
    district: 'Baleendah',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-08-25T17:00:00Z',
    ingestedAt: '2026-08-26T08:00:00Z',
    periodLabel: 'Agu 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: '850 rumah tergenang, pompa polder Cieunteung dioperasikan maksimal',
    metadata: {
      waterLevelCm: 80,
      polderStatus: 'Operasional',
    },
  },
  {
    id: 'inc-bdg-pasteur-flashflood',
    fingerprint: 'flood-pasteur-dr-djundjunan-2026-03',
    title: 'Banjir Cileuncang Simpang Pasteur - Jl. Dr. Djundjunan Kota Bandung',
    description: 'Luapan Sungai Citepus saat hujan ekstrem mengakibatkan genangan setinggi 50 cm di depan Mall BTC Pasteur, memicu kemacetan parah keluar masuk Gerbang Tol Pasteur.',
    category: 'FLOOD',
    subcategory: 'CILEUNCANG_DRAINASE',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Diskar PB Kota Bandung & Dishub Bandung',
    sourceUrl: 'https://diskarpb.bandung.go.id/',
    latitude: -6.8967,
    longitude: 107.5855,
    locationName: 'Jl. Dr. Djundjunan (Pasteur), Sukajadi',
    district: 'Sukajadi',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-03-12T16:15:00Z',
    ingestedAt: '2026-03-12T18:00:00Z',
    periodLabel: 'Mar 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Lalu lintas Tol Pasteur lumpuh 3 jam, belasan kendaraan roda dua mogok',
    metadata: {
      drainageIssue: 'Penyempitan gorong-gorong Citepus',
    },
  },
  {
    id: 'inc-bdg-gedebage-flood',
    fingerprint: 'flood-gedebage-soetta-2026-01',
    title: 'Genangan Banjir Arteri Gedebage & Pasar Induk Kota Bandung',
    description: 'Hujan lebat berjam-jam menyebabkan air antrean di saluran Sungai Cinambo meluap ke Jalan Soekarno-Hatta depan Pasar Induk Gedebage.',
    category: 'FLOOD',
    subcategory: 'GENANGAN_JALAN',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BPBD Kota Bandung & Dinas SDA Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.9482,
    longitude: 107.6841,
    locationName: 'Kawasan Pasar Induk Gedebage, Soekarno-Hatta',
    district: 'Gedebage',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-01-20T18:40:00Z',
    ingestedAt: '2026-01-21T09:00:00Z',
    periodLabel: 'Jan 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Jalan Soekarno-Hatta tergenang 40 cm sepanjang 300 meter',
    metadata: {},
  },

  // --- TRAFFIC & ROAD ACCIDENTS (KORLANTAS / KNKT / JASA MARGA) ---
  {
    id: 'inc-traffic-cipularang-km92',
    fingerprint: 'traffic-tol-cipularang-km92-2026-09',
    title: 'Kecelakaan Beruntun Tol Cipularang KM 92 Arah Jakarta',
    description: 'Truk muatan berat mengalami kegagalan fungsi pengereman (rem blong) pada turunan tajam Tol Cipularang KM 92, menabrak beruntun 11 kendaraan roda empat yang sedang melambat karena kepadatan lalu lintas.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_BERUNTUN_TOL',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PJR Korlantas Polri & Jasa Marga Traffic Information',
    sourceUrl: 'https://jasamarga.com/',
    latitude: -6.6432,
    longitude: 107.4121,
    locationName: 'Ruas Jalan Tol Cipularang KM 92 (Purwakarta - Bandung)',
    district: 'Sukatani',
    regencyCity: 'Kabupaten Purwakarta / Koridor Bandung Raya',
    province: 'Jawa Barat',
    occurredAt: '2026-09-08T15:20:00Z',
    ingestedAt: '2026-09-08T16:05:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 1,
    casualtiesInjured: 14,
    impactSummary: 'Tol Cipularang ditutup arah Jakarta selama 4 jam, 12 kendaraan rusak berat',
    metadata: {
      investigationBody: 'KNKT & Korlantas Polri',
      causeFactor: 'Rem blong pada kontur turunan terjal',
      vehicleTypes: ['Truk Kontainer', 'Minibus', 'Sedan'],
    },
  },
  {
    id: 'inc-traffic-soetta-bandung-2026',
    fingerprint: 'traffic-soetta-mohammad-toha-2026-09',
    title: 'Kecelakaan Fatal Jalur Arteri Soekarno-Hatta - Moh. Toha Bandung',
    description: 'Truk tangki menabrak separator jalan dan dua sepeda motor di perempatan by-pass Jl. Soekarno-Hatta persimpangan Moh. Toha saat cuaca hujan gerimis.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_LALU_LINTAS_KOTA',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'Satlantas Polrestabes Bandung & Dishub Kota Bandung',
    sourceUrl: 'https://korlantas.polri.go.id/',
    latitude: -6.9538,
    longitude: 107.6119,
    locationName: 'Simpang Empat By-pass Soekarno Hatta - Moh Toha',
    district: 'Regol',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-09-19T07:15:00Z',
    ingestedAt: '2026-09-19T08:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 2,
    casualtiesInjured: 3,
    impactSummary: 'Kemacetan panjang 4 km di jalur cepat Soekarno-Hatta arah barat',
    metadata: {
      roadType: 'Jalan Nasional Arteri Primer',
      weatherCondition: 'Hujan Gerimis / Jalan Licin',
    },
  },
  {
    id: 'inc-traffic-nagreg-2026',
    fingerprint: 'traffic-jalur-nagreg-leles-2026-04',
    title: 'Kecelakaan Tunggal Truk Terguling Tanjakan Nagreg',
    description: 'Truk pengangkut semen gagal menanjak di tikungan tajam Jalur Lingkar Nagreg akibat muatan berlebih (ODOL), lalu mundur dan terbalik menutup 2 lajur jalan.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KECELAKAAN_TUNGGAL_ODOL',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Korlantas Polri via BPS & Dishub Jabar',
    sourceUrl: 'https://jabar.bps.go.id/',
    latitude: -7.0261,
    longitude: 107.8932,
    locationName: 'Jalur Lingkar Nagreg KM 37',
    district: 'Nagreg',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-04-14T05:30:00Z',
    ingestedAt: '2026-04-14T07:00:00Z',
    periodLabel: 'Apr 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 1,
    impactSummary: 'Jalur utama Bandung - Garut/Tasikmalaya dialihkan ke jalur lama',
    metadata: {
      overdimensionOverload: true,
    },
  },
  {
    id: 'inc-traffic-padaleunyi-km149',
    fingerprint: 'traffic-padaleunyi-km149-gedebage-2026-07',
    title: 'Insiden Tabrakan Beruntun 4 Mobil Tol Padaleunyi KM 149 Gedebage',
    description: 'Pengereman mendadak kendaraan di lajur cepat saat mendekati exit tol KM 149 Gedebage menyebabkan tabrakan karambol 4 minibus.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'TABRAKAN_JALUR_CEPAT_TOL',
    severity: 'MEDIUM',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Jasa Marga Traffic Monitoring & PJR Jabar',
    sourceUrl: 'https://jasamarga.com/',
    latitude: -6.9582,
    longitude: 107.6953,
    locationName: 'Jalan Tol Padaleunyi KM 149 (Dekat Stasiun KCIC Tegalluar)',
    district: 'Gedebage',
    regencyCity: 'Kota Bandung',
    province: 'Jawa Barat',
    occurredAt: '2026-07-28T11:45:00Z',
    ingestedAt: '2026-07-28T12:30:00Z',
    periodLabel: 'Jul 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 4,
    impactSummary: 'Lajur cepat tersendat 45 menit sebelum kendaraan dievakuasi ke bahu jalan',
    metadata: {},
  },

  // --- TRANSPORTATION ACCIDENT (KNKT INVESTIGATION) ---
  {
    id: 'inc-rail-cicalengka-knkt',
    fingerprint: 'knkt-ka-turangga-commuter-cicalengka',
    title: 'Kecelakaan Tabrakan Kereta Api KA Turangga vs KA Lokal Baraya',
    description: 'Tabrakan adu banteng (head-on collision) antara KA 65A Turangga relasi Surabaya-Bandung dan KA 350 Commuter Line Bandung Raya di petak jalan Cicalengka - Haurpugur KM 181.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KECELAKAAN_PERKERETAAPIAN',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'KNKT (Laporan Investigasi No. KNKT.24.01.01.01) & Kemenhub',
    sourceUrl: 'https://knkt.dephub.go.id/',
    latitude: -6.9789,
    longitude: 107.8242,
    locationName: 'Petak Jalan KM 181+700 Cicalengka - Haurpugur',
    district: 'Cicalengka',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2024-01-05T06:03:00Z',
    ingestedAt: '2024-01-05T08:00:00Z',
    periodLabel: 'Jan 2024',
    casualtiesFatal: 4,
    casualtiesInjured: 37,
    impactSummary: 'Jalur selatan lumpuh total 24 jam, lokomotif CC206 & CC201 rusak parah',
    metadata: {
      agency: 'Komite Nasional Keselamatan Transportasi (KNKT)',
      reportCode: 'KNKT.24.01.01.01',
      factor: 'Anomali transmisi data uncommanded blok mekanik ke elektrik',
    },
  },

  // --- SEISMIC ACTIVITY & FAULTS (BMKG & PVMBG) ---
  {
    id: 'inc-earthquake-lembang-garsela',
    fingerprint: 'quake-sesar-garsela-kab-bandung-2024-09',
    title: 'Gempa Bumi Dangkal M 5.0 Akibat Sesar Garsela Mengguncang Kertasari Bandung',
    description: 'Gempa tektonik darat dangkal kedalaman 10 km dipicu oleh deformasi batuan pada zona Sesar Garsela (Garut Selatan). Guncangan mencapai intensitas IV-V MMI di Kertasari dan Pangalengan, dirasakan nyata di Kota Bandung.',
    category: 'EARTHQUAKE',
    subcategory: 'SESAR_AKTIF_DARAT',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Pusat Gempa Bumi & Tsunami BMKG',
    sourceUrl: 'https://bmkg.go.id/',
    latitude: -7.1902,
    longitude: 107.6712,
    locationName: 'Kecamatan Kertasari & Bedeng, Kabupaten Bandung',
    district: 'Kertasari',
    regencyCity: 'Kabupaten Bandung',
    province: 'Jawa Barat',
    occurredAt: '2024-09-18T09:41:00Z',
    ingestedAt: '2024-09-18T10:00:00Z',
    periodLabel: 'Sep 2024',
    casualtiesFatal: 2,
    casualtiesInjured: 81,
    impactSummary: '4.483 bangunan rumah & fasilitas publik di Kertasari dan Pangalengan rusak',
    metadata: {
      magnitude: 5.0,
      depth: '10 km',
      faultSystem: 'Sesar Garsela (Segmen Rakutai)',
      mmiScale: 'V MMI Kertasari, III MMI Kota Bandung',
    },
  },

  // --- VOLCANIC ACTIVITY (PVMBG BULLETIN) ---
  {
    id: 'inc-volcano-tangkuban-parahu',
    fingerprint: 'volcano-tangkuban-parahu-level2-waspada',
    title: 'Aktivitas Gunung Api Tangkuban Parahu: Status Level II (Waspada)',
    description: 'Pusat Vulkanologi dan Mitigasi Bencana Geologi (PVMBG) menetapkan Status Waspada seiring peningkatan gempa hembusan dan emisi gas CO2 di Kawah Ratu. Masyarakat dilarang mendekati bibir kawah dalam radius 500 meter.',
    category: 'VOLCANO',
    subcategory: 'STATUS_GUNUNG_API',
    severity: 'MEDIUM',
    status: 'MONITORING',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PVMBG Badan Geologi Kementerian ESDM (MAGMA Indonesia)',
    sourceUrl: 'https://magma.esdm.go.id/',
    latitude: -6.7594,
    longitude: 107.6097,
    locationName: 'Kawah Ratu Gunung Tangkuban Parahu (Lembang - Subang)',
    district: 'Lembang',
    regencyCity: 'Kabupaten Bandung Barat',
    province: 'Jawa Barat',
    occurredAt: '2026-09-15T08:00:00Z',
    ingestedAt: '2026-09-15T09:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Radius rekomendasi bahaya 500 meter dari Kawah Ratu & Kawah Upas',
    metadata: {
      alertLevel: 'Level II (Waspada)',
      crater: 'Kawah Ratu',
      hazardRadiusMeters: 500,
    },
  },
  {
    id: 'inc-volcano-ruang-erupsi',
    fingerprint: 'volcano-ruang-level4-awas-erupsi',
    title: 'Erupsi Eksplosif Gunung Ruang Sulawesi Utara: Status Level IV (Awas)',
    description: 'Letusan kolom abu vulkanik mencapai ketinggian 3.000 meter di atas puncak. PVMBG menaikkan status ke Level IV (Awas) disertai ancaman lontaran batu pijar dan potensi gelombang tsunami akibat runtuhan material ke laut.',
    category: 'VOLCANO',
    subcategory: 'ERUPSI_EKSPLOSIF',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PVMBG - Badan Geologi & BNPB',
    sourceUrl: 'https://magma.esdm.go.id/',
    latitude: 2.3031,
    longitude: 125.3703,
    locationName: 'Pulau Ruang, Kabupaten Sitaro',
    district: 'Tagulandang',
    regencyCity: 'Kabupaten Kepulauan Siau Tagulandang Biaro',
    province: 'Sulawesi Utara',
    occurredAt: '2026-09-21T18:15:00Z',
    ingestedAt: '2026-09-22T06:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Evakuasi total seluruh penduduk Pulau Ruang radius bahaya 6 km',
    metadata: {
      alertLevel: 'Level IV (Awas)',
      columnHeightMeters: 3000,
      vonaNotice: 'RED',
    },
  },

  // --- INDUSTRIAL & ENVIRONMENTAL HAZARDS ---
  {
    id: 'inc-industrial-balongan-fire',
    fingerprint: 'industrial-kilang-balongan-pertamina',
    title: 'Insiden Kebakaran Tangki T-301 Kilang Minyak Balongan Pertamina',
    description: 'Ledakan dan kobaran api hebat membakar 4 tangki penyimpanan BBM kilang minyak RU VI Balongan Indramayu saat terjadi hujan deras disertai petir hebat.',
    category: 'INDUSTRIAL_ACCIDENT',
    subcategory: 'KEBAKARAN_KILANG_MIGAS',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Ditjen Migas ESDM & BPBD Indramayu',
    sourceUrl: 'https://migas.esdm.go.id/',
    latitude: -6.3683,
    longitude: 108.3842,
    locationName: 'Kilang Pertamina RU VI Balongan',
    district: 'Balongan',
    regencyCity: 'Kabupaten Indramayu',
    province: 'Jawa Barat',
    occurredAt: '2021-03-29T00:45:00Z',
    ingestedAt: '2021-03-29T03:00:00Z',
    periodLabel: 'Mar 2021',
    casualtiesFatal: 1,
    casualtiesInjured: 29,
    impactSummary: '1.000 warga diungsikan, pasokan BBM regional sempat dialihkan',
    metadata: {
      facilityType: 'Refinery Unit Oil & Gas Storage',
      causeFactor: 'Sambaran kilat petir saat cuaca ekstrem',
    },
  },
  {
    id: 'inc-industrial-cimahi-textile',
    fingerprint: 'industrial-pabrik-tekstil-cimahi-2026-06',
    title: 'Kebakaran Gudang Bahan Kimia & Kain Industri Tekstil Cimahi',
    description: 'Konsleting pada panel trafo listrik utama menyulut kobaran api di gudang penyimpanan zat pewarna tekstil di Kawasan Industri Cimahi Selatan.',
    category: 'INDUSTRIAL_ACCIDENT',
    subcategory: 'KEBAKARAN_PABRIK',
    severity: 'HIGH',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Damkar Kota Cimahi & Diskar PB Bandung',
    sourceUrl: 'https://cimahikota.go.id/',
    latitude: -6.8978,
    longitude: 107.5389,
    locationName: 'Kawasan Industri Cimahi Selatan (Batas Kota Bandung)',
    district: 'Cimahi Selatan',
    regencyCity: 'Kota Cimahi / Bandung Raya',
    province: 'Jawa Barat',
    occurredAt: '2026-06-19T21:10:00Z',
    ingestedAt: '2026-06-20T08:00:00Z',
    periodLabel: 'Jun 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 2,
    impactSummary: '12 armada damkar dikerahkan, kerugian ditaksir Rp 3,2 Miliar',
    metadata: {},
  },
  {
    id: 'inc-landslide-cisarua-lembang',
    fingerprint: 'landslide-kolonel-masturi-cisarua-2026-02',
    title: 'Bencana Tanah Longsor Tebing Jl. Kolonel Masturi Lembang',
    description: 'Tebing setinggi 25 meter mengalami longsor akibat erosi hujan lebat menutup total badan Jalan Kolonel Masturi penghubung Cimahi - Lembang Bandung Barat.',
    category: 'LANDSLIDE',
    subcategory: 'LONGSOR_TEBING_JALAN',
    severity: 'HIGH',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'BPBD Kabupaten Bandung Barat & Dinas Bina Marga Jabar',
    sourceUrl: 'https://dibi.bnpb.go.id/',
    latitude: -6.8213,
    longitude: 107.5768,
    locationName: 'Jalan Kolonel Masturi KM 4, Cisarua',
    district: 'Cisarua',
    regencyCity: 'Kabupaten Bandung Barat',
    province: 'Jawa Barat',
    occurredAt: '2026-02-17T19:30:00Z',
    ingestedAt: '2026-02-18T07:00:00Z',
    periodLabel: 'Feb 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 1,
    impactSummary: 'Jalan tertutup material longsor 15 meter, akses wisata dialihkan',
    metadata: {},
  },
  // --- BALIKPAPAN & KALIMANTAN TIMUR INCIDENTS ---
  {
    id: 'inc-bpp-muara-rapak-traffic',
    fingerprint: 'traffic-muara-rapak-balikpapan-2026',
    title: 'Kecelakaan Beruntun Turunan Simpang Muara Rapak Balikpapan',
    description: 'Kecelakaan lalu lintas akibat kegagalan pengereman truk tronton kontainer saat melintasi turunan curam simpang Muara Rapak Balikpapan Utara menabrak sejumlah kendaraan roda empat dan roda dua.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KECELAKAAN_KENDARAAN_BERAT',
    severity: 'CRITICAL',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'HISTORICAL',
    sourceName: 'Ditlantas Polda Kaltim & Korlantas Polri',
    sourceUrl: 'https://korlantas.polri.go.id/',
    latitude: -1.2425,
    longitude: 116.8378,
    locationName: 'Simpang Muara Rapak, Jl. Soekarno-Hatta KM 0',
    district: 'Balikpapan Utara',
    regencyCity: 'Kota Balikpapan',
    province: 'Kalimantan Timur',
    occurredAt: '2026-06-14T06:15:00Z',
    ingestedAt: '2026-06-14T08:00:00Z',
    periodLabel: 'Jun 2026',
    casualtiesFatal: 4,
    casualtiesInjured: 14,
    impactSummary: 'Jalan utama protokol Balikpapan terputus 4 jam, perbaikan separator jalan',
    metadata: {
      locationType: 'Turunan Tajam Perkotaan',
      vehicleTypes: ['Truk Kontainer', 'Mobil Pribadi', 'Sepeda Motor'],
    },
  },
  {
    id: 'inc-bpp-pertamina-refinery-fire',
    fingerprint: 'industrial-kilang-pertamina-ru-v-balikpapan',
    title: 'Insiden Flash Fire & Penanganan Kilang Pertamina RU V Balikpapan',
    description: 'Percikan api pada area jalur pipa unit fraksinasi kilang Pertamina Refinery Unit V Balikpapan memicu sistem proteksi darurat dan pemadaman terkontrol oleh tim HSSE.',
    category: 'INDUSTRIAL_ACCIDENT',
    subcategory: 'KEBAKARAN_KILANG_MIGAS',
    severity: 'HIGH',
    status: 'HISTORICAL_RECORD',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'PT Kilang Pertamina Internasional RU V & Disdamkar Balikpapan',
    sourceUrl: 'https://pertamina.com/',
    latitude: -1.2678,
    longitude: 116.8242,
    locationName: 'Kilang Minyak Pertamina RU V, Jl. Yos Sudarso',
    district: 'Balikpapan Kota',
    regencyCity: 'Kota Balikpapan',
    province: 'Kalimantan Timur',
    occurredAt: '2026-05-20T10:30:00Z',
    ingestedAt: '2026-05-20T11:15:00Z',
    periodLabel: 'Mei 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 1,
    impactSummary: 'Kondisi operasional kilang tetap aman, isolasi jalur pipa selesai dalam 45 menit',
    metadata: {
      industryType: 'Refinery Migas',
      containmentStatus: 'Controlled',
    },
  },
  {
    id: 'inc-bpp-mt-haryono-flood',
    fingerprint: 'flood-mt-haryono-beller-balikpapan-2026',
    title: 'Banjir Genangan Arteri Jl. MT Haryono & Kawasan Beller Balikpapan',
    description: 'Hujan deras berdurasi > 3 jam memicu antrean air di Daerah Aliran Sungai (DAS) Ampal sehingga merendam badan jalan MT Haryono setinggi 40 - 75 cm memutus lalu lintas utama.',
    category: 'FLOOD',
    subcategory: 'GENANGAN_PERKOTAAN',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'BPBD Kota Balikpapan & DPU Kota Balikpapan',
    sourceUrl: 'https://bpbd.balikpapan.go.id/',
    latitude: -1.2335,
    longitude: 116.8624,
    locationName: 'Jl. MT Haryono (Kawasan Beller), Balikpapan Selatan',
    district: 'Balikpapan Selatan',
    regencyCity: 'Kota Balikpapan',
    province: 'Kalimantan Timur',
    occurredAt: '2026-09-22T14:40:00Z',
    ingestedAt: '2026-09-22T15:20:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Ratusan kendaraan roda dua mogok, pengalihan lalu lintas ke jalur Ring Road Selatan',
    metadata: {
      waterLevelCm: 75,
      riverBasin: 'DAS Ampal Balikpapan',
    },
  },
  {
    id: 'inc-bpp-firms-hotspot-kaltim',
    fingerprint: 'hotspot-firms-balikpapan-timur-samboja-2026',
    title: 'Titik Panas Satelit FIRMS Koridor Balikpapan Timur - Samboja',
    description: 'Sensor satelit NASA VIIRS mendeteksi anomali termal vegetasi semak belukar kering dengan tingkat kepercayaan tinggi (FRP 26.8 MW) di batas kawasan Balikpapan Timur menuju Samboja IKN.',
    category: 'FIRE_HOTSPOT',
    subcategory: 'KARHUTLA_SATELIT',
    severity: 'HIGH',
    status: 'MONITORING',
    temporalStatus: 'NEAR_REALTIME',
    sourceName: 'NASA FIRMS VIIRS & BPBD Kaltim',
    sourceUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    latitude: -1.1890,
    longitude: 116.9450,
    locationName: 'Koridor Balikpapan Timur - Samboja',
    district: 'Balikpapan Timur',
    regencyCity: 'Kota Balikpapan',
    province: 'Kalimantan Timur',
    occurredAt: '2026-09-29T11:20:00Z',
    ingestedAt: '2026-09-29T12:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Patroli darat tim Manggala Agni dan pendinginan titik api terisolasi di lahan terbuka',
    metadata: {
      frpMw: 26.8,
      confidence: 'nominal',
      satellite: 'Suomi NPP / VIIRS',
    },
  },
  // --- BANTEN INCIDENTS ---
  {
    id: 'inc-btn-cibanten-flood',
    fingerprint: 'flood-cibanten-kasemen-serang-2026',
    title: 'Banjir Luapan Sungai Cibanten & Kasemen Kota Serang',
    description: 'Debit air kiriman dari hulu Bendungan Sindangheula meluap ke Sungai Cibanten, merendam kawasan pemukiman warga Kecamatan Kasemen dan Kota Serang hingga 80 cm.',
    category: 'FLOOD',
    subcategory: 'LUAPAN_SUNGAI',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'BPBD Provinsi Banten & BPBD Kota Serang',
    sourceUrl: 'https://bpbd.bantenprov.go.id/',
    latitude: -6.0425,
    longitude: 106.1580,
    locationName: 'Kecamatan Kasemen, DAS Cibanten Kota Serang',
    district: 'Kasemen',
    regencyCity: 'Kota Serang',
    province: 'Banten',
    occurredAt: '2026-09-20T08:15:00Z',
    ingestedAt: '2026-09-20T09:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 2,
    impactSummary: '1.450 jiwa terdampak, 4 unit perahu karet evakuasi diturunkan di perumahan warga',
    metadata: {
      waterLevelCm: 80,
      riverBasin: 'DAS Cibanten',
    },
  },
  {
    id: 'inc-btn-cilegon-merak-traffic',
    fingerprint: 'traffic-pelabuhan-merak-cilegon-2026',
    title: 'Kemacetan Panjang & Antrean Truk Logistik Arteri Pelabuhan Merak Cilegon',
    description: 'Lonjakan volume kendaraan logistik penyeberangan Selat Sunda memicu antrean kendaraan hingga Gerbang Tol Merak KM 98, kepolisian memberlakukan delaying system di rest area.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'KEMACETAN_LOGISTIK_PENYEBERANGAN',
    severity: 'MEDIUM',
    status: 'MONITORING',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'Ditlantas Polda Banten & ASDP Indonesia Ferry',
    sourceUrl: 'https://banten.polri.go.id/',
    latitude: -5.9342,
    longitude: 105.9985,
    locationName: 'Akses Pelabuhan Penyeberangan Merak, Cilegon',
    district: 'Pulomerak',
    regencyCity: 'Kota Cilegon',
    province: 'Banten',
    occurredAt: '2026-09-25T16:00:00Z',
    ingestedAt: '2026-09-25T17:10:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Waktu tunggu penyeberangan 3 - 5 jam, delaying system diaktifkan di KM 43 & 68 Tol Tangerang-Merak',
    metadata: {
      corridor: 'Tol Tangerang - Merak KM 98',
    },
  },
  {
    id: 'inc-btn-ujungkulon-hotspot',
    fingerprint: 'hotspot-firms-ujung-kulon-pandeglang-2026',
    title: 'Titik Panas Satelit FIRMS Pesisir Pandeglang - Ujung Kulon',
    description: 'Satelit NASA FIRMS mendeteksi hotspot anomali termal vegetasi kering di kawasan penyangga Taman Nasional Ujung Kulon Kabupaten Pandeglang.',
    category: 'FIRE_HOTSPOT',
    subcategory: 'KARHUTLA_SATELIT',
    severity: 'HIGH',
    status: 'MONITORING',
    temporalStatus: 'NEAR_REALTIME',
    sourceName: 'NASA FIRMS & Balai TN Ujung Kulon',
    sourceUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    latitude: -6.7120,
    longitude: 105.4850,
    locationName: 'Kawasan Pesisir Sumur - Ujung Kulon, Pandeglang',
    district: 'Sumur',
    regencyCity: 'Kabupaten Pandeglang',
    province: 'Banten',
    occurredAt: '2026-09-28T13:45:00Z',
    ingestedAt: '2026-09-28T14:30:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Patroli darat tim gabungan polisi kehutanan dan damkar setempat memastikan tidak merambat ke zona inti',
    metadata: {
      frpMw: 19.4,
      confidence: 'nominal',
    },
  },
  {
    id: 'inc-aceh-krueng-flood',
    fingerprint: 'flood-krueng-aceh-banda-aceh-2026-09-28',
    title: 'Banjir Luapan Krueng Aceh Menggenangi Pemukiman Banda Aceh & Aceh Besar',
    description: 'Intensitas hujan tinggi selama 8 jam di hulu Jantho mengakibatkan DAS Krueng Aceh meluap. Genangan 40-70 cm merendam kawasan Peunayong, Lueng Bata, dan Ingin Jaya Aceh Besar.',
    category: 'FLOOD',
    subcategory: 'BANJIR_LUAPAN_KRUENG_ACEH',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'BPBD Kota Banda Aceh & BPBA',
    sourceUrl: 'https://bpba.acehprov.go.id/',
    latitude: 5.5532,
    longitude: 95.3218,
    locationName: 'Banda Aceh (DAS Krueng Aceh)',
    district: 'Lueng Bata',
    regencyCity: 'Kota Banda Aceh',
    province: 'Aceh',
    occurredAt: '2026-09-28T04:30:00Z',
    ingestedAt: '2026-09-28T05:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: '350 KK terdampak, pompa air pengendali banjir Pelabuhan Krueng Aceh diaktifkan',
    metadata: {
      waterLevelCm: 70,
      pumpStatus: 'Active 4 Units',
    },
  },
  {
    id: 'inc-aceh-seulimeum-eq',
    fingerprint: 'earthquake-seulimeum-aceh-besar-2026-09-27',
    title: 'Gempa Tektonik M5.2 Sesar Besar Sumatera Segmen Seulimeum Terasa di Banda Aceh',
    description: 'BMKG mencatat gempa dangkal M5.2 dengan kedalaman 10 km berpusat di darat 18 km tenggara Banda Aceh. Guncangan dirasakan III-IV MMI di Banda Aceh, Aceh Besar, dan Sigli Pidie.',
    category: 'EARTHQUAKE',
    subcategory: 'GEMPA_SESAR_SUMATERA_SEULIMEUM',
    severity: 'MEDIUM',
    status: 'MONITORING',
    temporalStatus: 'REALTIME',
    sourceName: 'Pusat Gempa Bumi & Tsunami BMKG',
    sourceUrl: 'https://warning.bmkg.go.id/',
    latitude: 5.4120,
    longitude: 95.4520,
    locationName: 'Seulimeum, Aceh Besar',
    district: 'Seulimeum',
    regencyCity: 'Kabupaten Aceh Besar',
    province: 'Aceh',
    occurredAt: '2026-09-27T14:15:00Z',
    ingestedAt: '2026-09-27T14:20:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Tidak berpotensi tsunami, getaran dirasakan nyata di dalam rumah',
    metadata: {
      magnitude: 5.2,
      depthKm: 10,
      mmiScale: 'III-IV MMI',
      faultSegment: 'Great Sumatran Fault (Seulimeum Segment)',
    },
  },
  {
    id: 'inc-aceh-kulu-traffic',
    fingerprint: 'traffic-gunung-kulu-aceh-lintas-barat-2026',
    title: 'Kecelakaan Bus Antarkota & Truk di Jalur Arteri Banda Aceh - Meulaboh Km 42',
    description: 'Kecelakaan melibatkan bus AKAP dan truk muatan di tikungan tajam tanjakan Gunung Kulu Km 42 Lintas Barat Aceh. Ditlantas Polda Aceh dan Dishub menerapkan rekayasa buka-tutup jalur.',
    category: 'TRAFFIC_ACCIDENT',
    subcategory: 'LAKA_LANTAS_ARTERY_JALUR_BARAT',
    severity: 'HIGH',
    status: 'RESOLVED',
    temporalStatus: 'VERIFIED_REPORT',
    sourceName: 'Ditlantas Polda Aceh & Pos Lantas Gunung Kulu',
    sourceUrl: 'https://korlantas.polri.go.id/',
    latitude: 5.3125,
    longitude: 95.2680,
    locationName: 'Jalan Lintas Banda Aceh - Meulaboh Km 42, Gunung Kulu',
    district: 'Lhoong',
    regencyCity: 'Kabupaten Aceh Besar',
    province: 'Aceh',
    occurredAt: '2026-09-25T11:20:00Z',
    ingestedAt: '2026-09-25T12:00:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 3,
    impactSummary: 'Arus lalu lintas kembali lancar pasca evakuasi armada derek Ditlantas',
    metadata: {
      roadClass: 'Jalan Nasional Lintas Barat Sumatera',
      towTrucksDispatched: 2,
    },
  },
  {
    id: 'inc-aceh-nagan-firms',
    fingerprint: 'fire-hotspot-nagan-raya-suak-puntong-2026-09-29',
    title: 'Titik Panas (Hotspot) Lahan Gambut Terdeteksi di Nagan Raya & Aceh Barat',
    description: 'Sensor satelit MODIS & VIIRS mendeteksi 6 hotspot tingkat kepercayaan tinggi (>80%) di area lahan gambut Suak Puntong. Tim gabungan Manggala Agni dan BPBD melakukan pemadaman darat.',
    category: 'FIRE_HOTSPOT',
    subcategory: 'KARHUTLA_LAHAN_GAMBUT',
    severity: 'HIGH',
    status: 'ACTIVE',
    temporalStatus: 'REALTIME',
    sourceName: 'NASA FIRMS & Manggala Agni Daops Sumatera',
    sourceUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    latitude: 4.1950,
    longitude: 96.2850,
    locationName: 'Suak Puntong, Nagan Raya',
    district: 'Kuala Pesisir',
    regencyCity: 'Kabupaten Nagan Raya',
    province: 'Aceh',
    occurredAt: '2026-09-29T13:40:00Z',
    ingestedAt: '2026-09-29T14:10:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Kanal blocking dan sekat bakar difungsikan untuk isolasi rembetan api',
    metadata: {
      brightnessKelvin: 334.2,
      confidencePct: 88,
      frpMw: 32.5,
    },
  },
  {
    id: 'inc-aceh-sabang-weather',
    fingerprint: 'weather-marine-sabang-uleelheue-2026-09-30',
    title: 'Peringatan Gelombang Tinggi & Angin Kencang Penyeberangan Banda Aceh - Sabang',
    description: 'BMKG Stasiun Meteorologi Sultan Iskandar Muda mengeluarkan peringatan angin kencang hingga 35 knot dan gelombang mencapai 2.5 - 4.0 meter di perairan Sabang dan Selat Malaka utara.',
    category: 'SEVERE_WEATHER',
    subcategory: 'GELOMBANG_TINGGI_PENYEBERANGAN',
    severity: 'MEDIUM',
    status: 'MONITORING',
    temporalStatus: 'REALTIME',
    sourceName: 'BMKG Stasiun Meteorologi Kelas I Sultan Iskandar Muda Banda Aceh',
    sourceUrl: 'https://maritim.bmkg.go.id/',
    latitude: 5.5685,
    longitude: 95.2810,
    locationName: 'Pelabuhan Penyeberangan Ulee Lheue, Banda Aceh',
    district: 'Meuraxa',
    regencyCity: 'Kota Banda Aceh',
    province: 'Aceh',
    occurredAt: '2026-09-30T08:00:00Z',
    ingestedAt: '2026-09-30T08:15:00Z',
    periodLabel: 'Sep 2026',
    casualtiesFatal: 0,
    casualtiesInjured: 0,
    impactSummary: 'Pemberangkatan KMP BRR & Express Bahari disesuaikan dengan kondisi ombak terkini',
    metadata: {
      waveHeightMeters: '2.5 - 4.0',
      windSpeedKnots: 35,
    },
  },
];
